### PR TITLE
Update to Chromium 126.0.6478.126

### PR DESCRIPTION
**Pull request by networkException**
This PR updates to Chromium 126.0.6478.126.
There were no changes needed on our end.

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/126.0.6478.114..126.0.6478.126?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_24.html)

### CODE REVIEW

**Comment by networkException** [comment]
I'll test #2926 before this, if all goes well and we can merge that I'll rebase the bump ofc

**Review by PF4Public — APPROVED** [review]

**Comment by rany2** [comment]
Why doesn't this get merged seeing it's ready and then we make a new revision when that other patch is for sure ready? I feel like we should just make -2 revisions instead of trying to keep UGC and Chromium versions one-to-one?

**Review by Ahrotahn — APPROVED** [review]
Either way should be fine!

**Comment by networkException** [comment]
Well sure, I'm not trying to keep chromium version one to one. Now the other pr is only blocked by my review though and I don't see an issue just doing both :)

**Pull request merged**
