### PR TITLE
Update to Chromium 106.0.5249.62

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 106.0.5249.62.

Notable changes:

* Small change added to fix-building-with-prunned-binaries due to [[3830821]](https://chromium-review.googlesource.com/c/chromium/src/+/3830821).  This should be a short-lived change since [[3845194]](https://chromium-review.googlesource.com/c/chromium/src/+/3845194) will resolve this in a future release.

* Removal in remove-unused-preferences-fields due to [[3794248]](https://chromium-review.googlesource.com/c/chromium/src/+/3794248)

* Removal in the inox safebrowsing patch due to [[3791366]](https://chromium-review.googlesource.com/c/chromium/src/+/3791366) adding the safebrowsing buildflag.

* Some additions to the safebrowsing patch due to [[3779761]](https://chromium-review.googlesource.com/c/chromium/src/+/3779761) and [[3829770]](https://chromium-review.googlesource.com/c/chromium/src/+/3829770). And removals due to the fixes in [[3791267]](https://chromium-review.googlesource.com/c/chromium/src/+/3791267), [[3791924]](https://chromium-review.googlesource.com/c/chromium/src/+/3791924), and [[3791365]](https://chromium-review.googlesource.com/c/chromium/src/+/3791365).

* Lots of small adjustments due to [[3887802]](https://chromium-review.googlesource.com/c/chromium/src/+/3887802)

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/105.0.5195.127..106.0.5249.62?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2022/09/stable-channel-update-for-desktop_27.html)

### CODE REVIEW

**Comment by a61kt** [comment]
compiling

**Review by networkException — APPROVED** [review]
LGTM

**Comment by networkException** [comment]
I think we have to bypass approvals on this one as PF4Public is hopefully on their well deserved vacation (unless another core team member steps in, of course :slightly_smiling_face:)

**Comment by a61kt** [comment]
@networkException im compiling it >)

and im having issues with ffmpeg again >*

and 
* gentoo aint has patches/bigfixes https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/chromium-106.0.5249.61.ebuild
- **but**  chromium-dev commented it _(use chromium ffmpeg)_  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-dev

**Comment by a61kt** [comment]
new funny bugs with blink

```id play with chromium-dev bugfixes 
        'blink_enable_generated_code_formatting=false'
        'blink_symbol_level=0'

[15539s] [49470/51701] STAMP obj/third_party/blink/renderer/platform/heap/heap.inputdeps.stamp
[15539s] [49471/51701] CXX obj/third_party/blink/renderer/platform/platform/avif_image_decoder.o
[15539s] FAILED: obj/third_party/blink/renderer/platform/platform/avif_image_decoder.o 
[15540s] clang++ -MMD -MF obj/third_party/blink/renderer/platform/platform/avif_image_decoder.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DBLINK_PLATFORM_IMPLEMENTATION=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_WAYLAND_KHR -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DLIBYUV_DISABLE_NEON -DWTF_USE_WEBAUDIO_PFFFT=1 -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DU_IMPORT=U_EXPORT -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_SANDBOXED_POINTERS -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPGC_POINTER_COMPRESSION -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_USE_X11 -DWEBRTC_USE_PIPEWIRE -DWEBRTC_DLOPEN_PIPEWIRE -DWEBRTC_USE_GIO -DLOGGING_INSIDE_WEBRTC -DLEVELDB_PLATFORM_CHROMIUM=1 -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DUSE_SYSTEM_ZLIB=1 -DUSE_SYSTEM_LIBJPEG -I../../third_party/skia/include/private -I../../third_party/pffft/src -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/jsoncpp_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -Igen/shim_headers/libpng_shim -Igen/shim_headers/libwebp_shim -Igen/shim_headers/brotli_shim -Igen/third_party/dawn/include -I../../third_party/dawn/include -I../../third_party/khronos -I../../gpu -I../../third_party/vulkan-deps/vulkan-headers/src/include -Igen/shim_headers/re2_shim -I../../third_party/libyuv/include -Igen/shim_headers/opus_shim -Igen/shim_headers/snappy_shim -Igen/shim_headers/aom_shim -Igen/shim_headers/dav1d_shim -Igen/shim_headers/woff2_shim -Igen/shim_headers/avif_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/quiche/common/platform/default -I../../net/third_party/quiche/src -Igen/net/third_party/quiche/src -I../../third_party/ced/src -I../../v8/include -Igen/v8/include -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/libwebm/source -I../../third_party/mesa_headers -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/iccjpeg -I../../third_party/ots/src/include -I../../third_party/emoji-segmenter/src -I../../third_party/one_euro_filter/src -I../../third_party/libjxl/src/lib/include -I../../third_party/libjxl/gen_headers -Wimplicit-fallthrough -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -flto=thin -fsplit-lto-unit -fwhole-program-vtables -no-canonical-prefixes -ftrivial-auto-var-init=pattern -fno-omit-frame-pointer -fsanitize=cfi-vcall -fsanitize-ignorelist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wconversion -Wno-float-conversion -Wno-sign-conversion -Wno-implicit-float-conversion -Wno-implicit-int-conversion -Wglobal-constructors -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -DPROTOBUF_ALLOW_DEPRECATED=1 -I/usr/include/nss -I/usr/include/nspr -Wno-shadow -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -DAVIF_DLL -std=c++17 -Wno-trigraphs -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wno-builtin-macro-redefined -Wno-unknown-warning-option -c ../../third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc -o obj/third_party/blink/renderer/platform/platform/avif_image_decoder.o
[15540s] ../../third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc:161:10: error: use of undeclared identifier 'AVIF_PIXEL_FORMAT_COUNT'; did you mean 'AVIF_PIXEL_FORMAT_NONE'?
[15540s]     case AVIF_PIXEL_FORMAT_COUNT:
[15540s]          ^~~~~~~~~~~~~~~~~~~~~~~
[15540s]          AVIF_PIXEL_FORMAT_NONE
[15540s] /usr/include/avif/avif.h:191:5: note: 'AVIF_PIXEL_FORMAT_NONE' declared here
[15540s]     AVIF_PIXEL_FORMAT_NONE = 0,
[15540s]     ^
[15540s] ../../third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc:161:10: error: duplicate case value 'AVIF_PIXEL_FORMAT_NONE'
[15540s]     case AVIF_PIXEL_FORMAT_COUNT:
[15540s]          ^
[15540s] ../../third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc:160:10: note: previous case defined here
[15540s]     case AVIF_PIXEL_FORMAT_NONE:
[15540s]          ^
[15540s] ../../third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc:304:10: error: use of undeclared identifier 'AVIF_PIXEL_FORMAT_COUNT'; did you mean 'AVIF_PIXEL_FORMAT_NONE'?
[15540s]     case AVIF_PIXEL_FORMAT_COUNT:
[15540s]          ^~~~~~~~~~~~~~~~~~~~~~~
[15540s]          AVIF_PIXEL_FORMAT_NONE
[15540s] /usr/include/avif/avif.h:191:5: note: 'AVIF_PIXEL_FORMAT_NONE' declared here
[15540s]     AVIF_PIXEL_FORMAT_NONE = 0,
[15540s]     ^
[15540s] ../../third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc:304:10: error: duplicate case value 'AVIF_PIXEL_FORMAT_NONE'
[15540s]     case AVIF_PIXEL_FORMAT_COUNT:
[15540s]          ^
[15540s] ../../third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc:303:10: note: previous case defined here
[15540s]     case AVIF_PIXEL_FORMAT_NONE:
[15540s]          ^
[15540s] 4 errors generated.
```

**Comment by jstkdng** [comment]
the core team needs more ppl it seems

**Comment by teeminus** [comment]
Windows is compiling fine (with some minor updates to the patches).

**Comment by mbakke** [comment]
Works fine on Guix :+1:

**Comment by Ahrotahn** [comment]
@a61kt You would either have to build with the supplied libavif or with a system version that includes the changes in https://github.com/AOMediaCodec/libavif/commit/d22d4de94120

---

> the core team needs more ppl it seems

Yeah, it would help to have more people involved.  
Github gives me an option to bypass the review requirements.  I've never tried that before, but I figure I'll give it a go on my lunch break if no one else runs into any issues building.

**Comment by teeminus** [comment]
So no changes between .61 and .62 (for windows)?

**Review by networkException — APPROVED** [review]

**Comment by Ahrotahn** [comment]
@teeminus Yup!  Due to the way we're doing this I just added a new commit instead of doing a new PR.

**Pull request merged**
