### PR TITLE
Update to Chromium 113.0.5672.63/64

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 113.0.5672.63/64.

Notes:

* The Debian unrar patch has been removed due to the previous changes in 112 and now that [[4350049]](https://chromium-review.googlesource.com/c/chromium/src/+/4350049) has landed.

* A removal in the trk-prefixes patch due to [[4326947]](https://chromium-review.googlesource.com/c/chromium/src/+/4326947)

* disable-webrtc-log-uploader.patch had a small change and a new addition for [[4228430]](https://chromium-review.googlesource.com/c/chromium/src/+/4228430)

* The remove-unused-preferences patch had some updates for [[4348622]](https://chromium-review.googlesource.com/c/chromium/src/+/4348622) and new additions for [[4295717]](https://chromium-review.googlesource.com/c/chromium/src/+/4295717), [[4291250]](https://chromium-review.googlesource.com/c/chromium/src/+/4291250), and [[4323387]](https://chromium-review.googlesource.com/c/chromium/src/+/4323387)

<br>

Upstream fixes needed:

* An include was left out in web_view_impl.cc:  [[4376772]](https://chromium-review.googlesource.com/c/chromium/src/+/4376772)

* std::monospace was used in authenticator_request_dialog_model.h without including the correct header:  [[4372590]](https://chromium-review.googlesource.com/c/chromium/src/+/4372590)

<br>

Toolchain-related fixes:

<ul>
<li>download_bubble_update_service requires the iterators to be declared as subtypes in the template:
<details><summary>diff</summary>

```diff
--- a/chrome/browser/download/bubble/download_bubble_update_service.cc
+++ b/chrome/browser/download/bubble/download_bubble_update_service.cc
@@ -87,6 +87,7 @@
 // Helper to get an iterator to the last element in the cache. The cache
 // must not be empty.
 template <typename Item>
+typename
 SortedItems<Item>::iterator GetLastIter(SortedItems<Item>& cache) {
   CHECK(!cache.empty());
   auto it = cache.end();
@@ -789,8 +790,10 @@
 }
 
 template <typename Id, typename Item>
+typename
 SortedItems<Item>::iterator
 DownloadBubbleUpdateService::RemoveItemFromCacheByIter(
+    typename
     SortedItems<Item>::iterator iter,
     SortedItems<Item>& cache,
     IterMap<Id, Item>& iter_map) {
--- a/chrome/browser/download/bubble/download_bubble_update_service.h
+++ b/chrome/browser/download/bubble/download_bubble_update_service.h
@@ -208,7 +208,9 @@
 
   // Removes item if we already have the iterator to it. Returns next iterator.
   template <typename Id, typename Item>
+  typename
   SortedItems<Item>::iterator RemoveItemFromCacheByIter(
+      typename
       SortedItems<Item>::iterator iter,
       SortedItems<Item>& cache,
       IterMap<Id, Item>& iter_map);
```

</details></li></ul>

* A structured binding was added in [[4264071]](https://chromium-review.googlesource.com/c/chromium/src/+/4264071) triggering a bug fixed in https://github.com/llvm/llvm-project/commit/e1111e2056e7245b21e24816f6f7ef5ac016ed6f. If your version of clang doesn't yet include that fix then this change should work for now:  
<details style="padding-left: 2em"><summary>diff</summary>

```diff
--- a/third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc
+++ b/third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc
@@ -516,8 +516,11 @@
                                 row_auto_repetitions);
 
   bool has_nested_subgrid = false;
-  auto& [grid_items, layout_data, subtree_size] =
+  auto& sizing_data =
       sizing_tree->CreateSizingData();
+  auto& grid_items = sizing_data.grid_items;
+  auto& layout_data = sizing_data.layout_data;
+  auto& subtree_size = sizing_data.subtree_size;
 
   if (!must_ignore_children) {
     // Construct grid items that are not subgridded.
@@ -1540,8 +1543,11 @@
     NGGridSizingTree* sizing_tree) const {
   DCHECK(sizing_tree && current_grid_index < sizing_tree->Size());
 
-  auto& [grid_items, layout_data, subtree_size] =
+  auto& sizing_data =
       sizing_tree->At(current_grid_index);
+  auto& grid_items = sizing_data.grid_items;
+  auto& layout_data = sizing_data.layout_data;
+  auto& subtree_size = sizing_data.subtree_size;
 
   auto InitAndCacheTrackSizes = [&](GridTrackSizingDirection track_direction) {
     InitializeTrackCollection(opt_subgrid_data, track_direction, &layout_data);
```
</details>

<br><br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/112.0.5615.165..113.0.5672.64?pretty=fuller&n=10000)
[Blog Post](https://chromereleases.googleblog.com/2023/05/stable-channel-update-for-desktop.html)

### CODE REVIEW

**Comment by teeminus** [comment]
Hi, did you forget to include the changes for the `download_bubble_update_service` file? I get the following error message while compiling on windows:

```
In file included from ../../chrome/browser/extensions/api/downloads/downloads_api.cc:37:
In file included from ../..\chrome/browser/download/bubble/download_bubble_ui_controller.h:11:
../..\chrome/browser/download/bubble/download_bubble_update_service.h(211,3): error: missing 'typename' prior to dependent type name 'SortedItems<Item>::iterator'
  SortedItems<Item>::iterator RemoveItemFromCacheByIter(
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  typename
../..\chrome/browser/download/bubble/download_bubble_update_service.h(212,7): warning: missing 'typename' prior to dependent type name 'SortedItems<Item>::iterator' [-Wtypename-missing]
      SortedItems<Item>::iterator iter,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      typename
1 warning and 1 error generated.
```

I searched the patches for the file mentioned in your PR message, but I didn't find it.

**Comment by Ahrotahn** [comment]
The upstream and toolchain fixes are not included.  That's normally left for each platform to add since what is needed can vary depending on their setup.  Though we have added upstream patches in the past if it affects all platforms, if it's a large change, or if it somehow makes everyone's lives easier.

**Comment by teeminus** [comment]
If windows is the only platform affected I will include the patch in the windows PR.

**Comment by PF4Public** [comment]
> If windows is the only platform affected I will include the patch in the windows PR.

At which step did you encounter it? I just got to where `std::monospace` fails the build.

**Comment by teeminus** [comment]
> > If windows is the only platform affected I will include the patch in the windows PR.
> 
> 
> 
> At which step did you encounter it (major target and source item number)? I just got to where `std::monospace` fails the build, which was around 21000/24000 of <s>v8_context_snapshot_generator</s> chrome.

I don't remember where exactly it failed. 

Compiling finished by now but I had to include the second toolchain patch as well.

**Comment by PF4Public** [comment]
Builds and runs. Had to include only header-related patches. I'm building with clang-16, that is probably the reason, why I didn't need other patches.

**Comment by Ahrotahn** [comment]
Good catch!  I'm surprised they'd set up a define like that without default a return value.  I pushed a commit to fix that, which should be short-lived once [[4429593]](https://chromium-review.googlesource.com/c/chromium/src/+/4429593) lands.

**Review by PF4Public — APPROVED** [review]

**Comment by PF4Public** [comment]
BTW, do we need .64 for Windows?

**Comment by Ahrotahn** [comment]
Yes, but the tarball wasn't available until recently.

**Review by PF4Public — APPROVED** [review]

**Comment by teeminus** [comment]
.64 builds and runs fine on windows

**Comment by networkException** [comment]
Sorry for the delay, I just now got it take a look at this.

Usually I would just build the Arch Packaging but right now there's a gcc version missmatch, any idea how to get gcc13 patches?

**Comment by PF4Public** [comment]
> any idea how to get gcc13 patches?

https://github.com/PF4Public/gentoo-overlay/pull/217 ;)

**Review by networkException — APPROVED** [review]

**Pull request merged**
