### PR TITLE
Update actions

### PR DESCRIPTION
**Pull request by wrt54g**
I updated the github actions

### CODE REVIEW

**Comment by networkException** [comment]
Is there any benefit to this change?

**Comment by wrt54g** [comment]
@networkException They are dependency updates. Check the releases page for these actions to view the changes.

**Comment by networkException** [comment]
I know what the change is, I want to know if there's any benefit in upgrading from one stable branch to another. If there is none there's no point in making this change.

**Comment by wrt54g** [comment]
Just later versions:
https://github.com/actions/stale/releases/tag/v5.0.0
https://github.com/actions/checkout/releases/tag/v3.0.2

**Comment by wrt54g** [comment]
They now use nodejs v16 (or the stale action)

**Comment by PF4Public** [comment]
It would have been great if you tested these changes in you fork @wrt54g for some time (a month for example) to be sure it won't bring any surprises. That's what I was about to suggest, but since you've already closed this PR, well, whatever.

**Comment by networkException** [comment]
I don't really see the point of switching stable branch for the sake of updating :shrug:

**Pull request closed without merging**
