### PR TITLE
Apply referrer customizations to document.referrer

### PR DESCRIPTION
**Pull request by implicitfield**
Currently, referrer customizations (via the ```referrer-directive``` flag) only apply to the HTTP headers, and not to ```document.referrer```. This is problematic for a few reasons:
1. This mismatch makes the browser easily fingerprintable when the flag is set to anything but the default value.
2. ```document.referrer``` can used to trigger malicious code for certain referrers.
3. The current behaviour is simply quite counterintuitive.

<strike>This PR addresses that by adapting the existing referrer customization logic to the ```Referrer::SanitizeForRequest``` function. I've only applied it to the second overload of that function, as adding it to the first one didn't seem to impact anything.</strike>
EDIT: This PR now uses a different approach, where all locations that check ```enable_referrers``` (or a similar variable) are modified to call a new ```sanitize_referrer``` function, which checks a few newly added feature flags, namely:
- ```remove-cross-origin-referrers```
- ```minimal-referrers```

The reason for splitting the old ```referrer-directive``` into multiple feature flags was because other threads need to check values of these flags, which is something that switches don't support.
In addition, I've added a ```remove-referrers```  feature flag, which should behave exactly how ```--enable-features=NoReferrers``` behaves.

These changes can be tested by querying ```document.referrer``` in devtools with the appropriate flag set.

### CODE REVIEW

**Comment by PF4Public** [comment]
Will it somehow impact performance?

**Review by Ahrotahn — DISMISSED** [review]
Looks good to me, everything checks out in my build.

**Comment by PF4Public** [comment]
Merging this before the update to 113 will likely make the latter need rebasing. Should we merge it before or after that one?

**Comment by Ahrotahn** [comment]
Yes, it would be best to hold off on merging this until 113 is merged.  This PR shouldn't need any changes to be applied afterwards.

**Comment by Ahrotahn** [comment]
The new changes look good to me and worked as expected in my build.  
The only thing I can suggest is to update `docs/flags.md` to remove the old flag and add the new ones.

**Review by Ahrotahn — APPROVED** [review]

**Comment by networkException** [comment]
For me compilation fails with `../../net/base/referrer_sanitizer.h:9:10: fatal error: 'services/network/public/mojom/referrer_policy.mojom-shared.h' file not found`, did that regress in the most recent release?

**Comment by Ahrotahn** [comment]
It looks like `net/BUILD.gn` is missing `//services/network/public/mojom` in the public_deps, and I was lucky to have that header generated before getting to the new files.  It might be a better idea to move them to `content/public/common/` instead.

**Comment by Ahrotahn** [comment]
It seems the new location has a similar problem:
```
In file included from ../../src/chromium/content/public/common/referrer_sanitizer.cc:7:
../../src/chromium/chrome/common/chrome_features.h:18:10: fatal error: 'chrome/common/buildflags.h' file not found
```
I wasn't aware that chrome_features relied on a generated header before suggesting that location. Since this relies on the existing noreferrers flag it might be better to move the new files to `chrome/common`.  This time I tested the idea to be sure that wouldn't also run in to problems:
<details><summary>diff</summary>

```diff
--- a/patches/extra/ungoogled-chromium/add-flags-for-referrer-customization.patch
+++ b/patches/extra/ungoogled-chromium/add-flags-for-referrer-customization.patch
@@ -17,6 +17,25 @@
 +     "Removes all cross-origin referrers and strips same-origin referrers down to the origin. Has lower precedence than remove-cross-origin-referrers. ungoogled-chromium flag.",
 +     kOsAll, FEATURE_VALUE_TYPE(features::kMinimalReferrers)},
  #endif  // CHROME_BROWSER_UNGOOGLED_FLAG_ENTRIES_H_
+--- a/chrome/common/BUILD.gn
++++ b/chrome/common/BUILD.gn
+@@ -143,6 +143,8 @@ static_library("common_lib") {
+     "pref_names_util.cc",
+     "pref_names_util.h",
+     "ref_counted_util.h",
++    "referrer_sanitizer.cc",
++    "referrer_sanitizer.h",
+     "search/instant_mojom_traits.h",
+     "search/instant_types.cc",
+     "search/instant_types.h",
+@@ -267,6 +269,7 @@ static_library("common_lib") {
+     "//components/no_state_prefetch/common:mojo_bindings",
+     "//components/page_load_metrics/common:common",
+     "//components/password_manager/content/common",
++    "//services/network/public/mojom",
+   ]
+ 
+   if (enable_pdf) {
 --- a/chrome/common/chrome_features.cc
 +++ b/chrome/common/chrome_features.cc
 @@ -842,6 +842,14 @@ BASE_FEATURE(kNewMacNotificationAPI,
@@ -47,44 +66,8 @@
  #if BUILDFLAG(IS_WIN)
  COMPONENT_EXPORT(CHROME_FEATURES)
  BASE_DECLARE_FEATURE(kNotificationDurationLongForRequireInteraction);
---- a/content/browser/renderer_host/navigation_request.cc
-+++ b/content/browser/renderer_host/navigation_request.cc
-@@ -119,6 +119,7 @@
- #include "content/public/common/content_features.h"
- #include "content/public/common/content_switches.h"
- #include "content/public/common/network_service_util.h"
-+#include "content/public/common/referrer_sanitizer.h"
- #include "content/public/common/url_constants.h"
- #include "content/public/common/url_utils.h"
- #include "mojo/public/cpp/system/data_pipe.h"
-@@ -425,10 +426,10 @@ void AddAdditionalRequestHeaders(
-       net::HttpRequestHeaders::kUserAgent,
-       ComputeUserAgentValue(*headers, user_agent_override, browser_context));
- 
--  if (!render_prefs.enable_referrers) {
--    *referrer =
--        blink::mojom::Referrer(GURL(), network::mojom::ReferrerPolicy::kNever);
--  }
-+  auto sanitized_referrer = content::sanitize_referrer(
-+      referrer->url, url, referrer->policy, render_prefs.enable_referrers);
-+  *referrer = blink::mojom::Referrer(std::move(sanitized_referrer.first),
-+                                     std::move(sanitized_referrer.second));
- 
-   // Next, set the HTTP Origin if needed.
-   if (NeedsHTTPOrigin(headers, method)) {
---- a/content/public/common/BUILD.gn
-+++ b/content/public/common/BUILD.gn
-@@ -192,6 +192,8 @@ source_set("common_sources") {
-     "pseudonymization_util.h",
-     "referrer.cc",
-     "referrer.h",
-+    "referrer_sanitizer.cc",
-+    "referrer_sanitizer.h",
-     "referrer_type_converters.cc",
-     "referrer_type_converters.h",
-     "resource_request_blocked_reason.h",
 --- /dev/null
-+++ b/content/public/common/referrer_sanitizer.cc
++++ b/chrome/common/referrer_sanitizer.cc
 @@ -0,0 +1,48 @@
 +// Copyright 2023 The ungoogled-chromium Authors
 +// Use of this source code is governed by a BSD-style license that can be
@@ -95,7 +78,7 @@
 +#include "chrome/common/chrome_features.h"
 +#include "url/origin.h"
 +
-+namespace content {
++namespace referrer_sanitizer {
 +
 +static GURL sanitize_referrer_internal(const GURL& origin,
 +                                       const GURL& destination) {
@@ -133,51 +116,75 @@
 +          referrer_policy};
 +}
 +
-+}  // namespace content
++}  // namespace referrer_sanitizer
 --- /dev/null
-+++ b/content/public/common/referrer_sanitizer.h
-@@ -0,0 +1,31 @@
++++ b/chrome/common/referrer_sanitizer.h
+@@ -0,0 +1,30 @@
 +// Copyright 2023 The ungoogled-chromium Authors
 +// Use of this source code is governed by a BSD-style license that can be
 +// found in the LICENSE file.
 +
-+#ifndef CONTENT_PUBLIC_COMMON_REFERRER_SANITIZER_H_
-+#define CONTENT_PUBLIC_COMMON_REFERRER_SANITIZER_H_
++#ifndef CHROME_COMMON_REFERRER_SANITIZER_H_
++#define CHROME_COMMON_REFERRER_SANITIZER_H_
 +
 +#include <string>
 +#include <utility>
-+#include "content/common/content_export.h"
 +#include "net/url_request/referrer_policy.h"
 +#include "services/network/public/mojom/referrer_policy.mojom-shared.h"
 +#include "url/gurl.h"
 +
-+namespace content {
++namespace referrer_sanitizer {
 +
-+CONTENT_EXPORT std::pair<GURL, net::ReferrerPolicy> sanitize_referrer(
++std::pair<GURL, net::ReferrerPolicy> sanitize_referrer(
 +    const GURL& origin,
 +    const GURL& destination,
 +    const net::ReferrerPolicy& referrer_policy,
 +    bool enable_referrers);
 +
-+CONTENT_EXPORT std::pair<GURL, network::mojom::ReferrerPolicy>
-+sanitize_referrer(const GURL& origin,
-+                  const GURL& destination,
-+                  const network::mojom::ReferrerPolicy& referrer_policy,
-+                  bool enable_referrers);
++std::pair<GURL, network::mojom::ReferrerPolicy> sanitize_referrer(
++    const GURL& origin,
++    const GURL& destination,
++    const network::mojom::ReferrerPolicy& referrer_policy,
++    bool enable_referrers);
 +
-+}  // namespace content
++}  // namespace referrer_sanitizer
 +
-+#endif  // CONTENT_PUBLIC_COMMON_REFERRER_SANITIZER_H_
++#endif  // CHROME_COMMON_REFERRER_SANITIZER_H_
+--- a/content/browser/renderer_host/navigation_request.cc
++++ b/content/browser/renderer_host/navigation_request.cc
+@@ -39,6 +39,7 @@
+ #include "base/types/pass_key.h"
+ #include "build/build_config.h"
+ #include "build/chromeos_buildflags.h"
++#include "chrome/common/referrer_sanitizer.h"
+ #include "components/attribution_reporting/os_registration.h"
+ #include "components/attribution_reporting/os_support.mojom.h"
+ #include "content/browser/attribution_reporting/attribution_manager.h"
+@@ -425,10 +426,10 @@ void AddAdditionalRequestHeaders(
+       net::HttpRequestHeaders::kUserAgent,
+       ComputeUserAgentValue(*headers, user_agent_override, browser_context));
+ 
+-  if (!render_prefs.enable_referrers) {
+-    *referrer =
+-        blink::mojom::Referrer(GURL(), network::mojom::ReferrerPolicy::kNever);
+-  }
++  auto sanitized_referrer = referrer_sanitizer::sanitize_referrer(
++      referrer->url, url, referrer->policy, render_prefs.enable_referrers);
++  *referrer = blink::mojom::Referrer(std::move(sanitized_referrer.first),
++                                     std::move(sanitized_referrer.second));
+ 
+   // Next, set the HTTP Origin if needed.
+   if (NeedsHTTPOrigin(headers, method)) {
 --- a/content/renderer/render_frame_impl.cc
 +++ b/content/renderer/render_frame_impl.cc
-@@ -71,6 +71,7 @@
- #include "content/public/common/content_switches.h"
- #include "content/public/common/extra_mojo_js_features.mojom.h"
- #include "content/public/common/isolated_world_ids.h"
-+#include "content/public/common/referrer_sanitizer.h"
- #include "content/public/common/url_constants.h"
- #include "content/public/common/url_utils.h"
- #include "content/public/renderer/content_renderer_client.h"
+@@ -52,6 +52,7 @@
+ #include "build/chromeos_buildflags.h"
+ #include "cc/base/switches.h"
+ #include "cc/trees/ukm_manager.h"
++#include "chrome/common/referrer_sanitizer.h"
+ #include "content/common/associated_interfaces.mojom.h"
+ #include "content/common/content_navigation_policy.h"
+ #include "content/common/content_switches_internal.h"
 @@ -4249,10 +4250,13 @@ void RenderFrameImpl::WillSendRequestInt
  
    request.SetHasUserGesture(frame_->HasTransientUserActivation());
@@ -186,7 +193,7 @@
 -    request.SetReferrerString(WebString());
 -    request.SetReferrerPolicy(network::mojom::ReferrerPolicy::kNever);
 -  }
-+  auto sanitized_referrer = content::sanitize_referrer(
++  auto sanitized_referrer = referrer_sanitizer::sanitize_referrer(
 +      WebStringToGURL(request.ReferrerString()),
 +      WebStringToGURL(request.Url().GetString()), request.GetReferrerPolicy(),
 +      GetWebView()->GetRendererPreferences().enable_referrers);
@@ -198,14 +205,14 @@
  void RenderFrameImpl::DidLoadResourceFromMemoryCache(
 --- a/services/network/network_service_network_delegate.cc
 +++ b/services/network/network_service_network_delegate.cc
-@@ -13,6 +13,7 @@
+@@ -12,6 +12,7 @@
+ #include "base/strings/utf_string_conversions.h"
  #include "base/types/optional_util.h"
  #include "build/build_config.h"
++#include "chrome/common/referrer_sanitizer.h"
  #include "components/domain_reliability/monitor.h"
-+#include "content/public/common/referrer_sanitizer.h"
  #include "net/base/features.h"
  #include "net/base/isolation_info.h"
- #include "net/base/load_flags.h"
 @@ -59,9 +60,14 @@ NetworkServiceNetworkDelegate::~NetworkS
  void NetworkServiceNetworkDelegate::MaybeTruncateReferrer(
      net::URLRequest* const request,
@@ -214,9 +221,9 @@
 -    request->SetReferrer(std::string());
 -    request->set_referrer_policy(net::ReferrerPolicy::NO_REFERRER);
 +
-+  auto sanitized_referrer =
-+      content::sanitize_referrer(GURL(request->referrer()), effective_url,
-+                                 request->referrer_policy(), enable_referrers_);
++  auto sanitized_referrer = referrer_sanitizer::sanitize_referrer(
++      GURL(request->referrer()), effective_url,
++      request->referrer_policy(), enable_referrers_);
 +  if (sanitized_referrer.first != effective_url.spec() ||
 +      sanitized_referrer.second != request->referrer_policy()) {
 +    request->SetReferrer(sanitized_referrer.first.spec());
@@ -230,7 +237,7 @@
  #include "base/ranges/algorithm.h"
  #include "base/synchronization/waitable_event.h"
  #include "base/task/single_thread_task_runner.h"
-+#include "content/public/common/referrer_sanitizer.h"
++#include "chrome/common/referrer_sanitizer.h"
  #include "mojo/public/cpp/bindings/pending_remote.h"
  #include "services/network/public/cpp/wrapper_shared_url_loader_factory.h"
  #include "third_party/blink/public/common/loader/loader_constants.h"
@@ -247,7 +254,7 @@
 -    request.SetReferrerString(WebString());
 -    request.SetReferrerPolicy(network::mojom::ReferrerPolicy::kNever);
 -  }
-+  auto sanitized_referrer = content::sanitize_referrer(
++  auto sanitized_referrer = referrer_sanitizer::sanitize_referrer(
 +      WebStringToGURL(request.ReferrerString()),
 +      WebStringToGURL(request.Url().GetString()), request.GetReferrerPolicy(),
 +      renderer_preferences_.enable_referrers);
@@ -263,7 +270,7 @@
  #include "base/task/sequenced_task_runner.h"
  #include "base/task/single_thread_task_runner.h"
  #include "base/task/thread_pool.h"
-+#include "content/public/common/referrer_sanitizer.h"
++#include "chrome/common/referrer_sanitizer.h"
  #include "services/network/public/cpp/wrapper_shared_url_loader_factory.h"
  #include "third_party/blink/public/common/features.h"
  #include "third_party/blink/public/common/loader/loader_constants.h"
@@ -283,7 +290,7 @@
 -    request.SetReferrerString(WebString());
 -    request.SetReferrerPolicy(network::mojom::ReferrerPolicy::kNever);
 -  }
-+  auto sanitized_referrer = content::sanitize_referrer(
++  auto sanitized_referrer = referrer_sanitizer::sanitize_referrer(
 +      WebStringToGURL(request.ReferrerString()),
 +      WebStringToGURL(request.Url().GetString()), request.GetReferrerPolicy(),
 +      renderer_preferences_.enable_referrers);
```
</details>

**Review by Ahrotahn — APPROVED** [review]

**Review by networkException — APPROVED** [review]

**Comment by PF4Public** [comment]
@implicitfield  All in all was the original functionality preserved?

**Comment by PF4Public** [comment]
@implicitfield Awesome, thanks!

**Pull request merged**
