### PR TITLE
Update to Chromium 118.0.5993.88

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 118.0.5993.88.
There were no notable changes needed on our end.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/118.0.5993.70..118.0.5993.88?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2023/10/stable-channel-update-for-desktop_17.html)

### CODE REVIEW

**Comment by PF4Public** [comment]
Maybe we should also release .71 for Windows as containing the fix before .89 goes to stable on Windows?

**Comment by Ahrotahn** [comment]
It seems like since .71 the trailing release is only for the Extended Stable channel now.  If you check out [the dash for windows](https://chromiumdash.appspot.com/releases?platform=Windows) .89 is also in Extended but not Stable.  Currently there is no tarball available for it, so maybe we shouldn't bother with those releases now?  They usually were only version bumps anyways.

**Comment by PF4Public** [comment]
> there is no tarball available for it

Still no tarball? Shame.

We can hope that 89 comes to Windows fast enough.

**Review by PF4Public — APPROVED** [review]

**Comment by teeminus** [comment]
Maybe we should switch to the git approach for windows to be able to release updates when no tarball is available.

**Comment by PF4Public** [comment]
> Maybe we should switch to the git approach for windows to be able to release updates when no tarball is available.

Would it be doable w.r.t. changes in respective repo?

**Comment by teeminus** [comment]
I tested the git method back when it was developed. It was not a big deal to change the windows build script. We could even keep the tarball method as a commandline option.

Unfortunately, I am currently out of town and won't be able to work on both this update and the git integration before next monday.

**Review by networkException — APPROVED** [review]

**Pull request merged**
