### PR TITLE
Fix for close confirmation

### LINKED ISSUE #2917: add-flag-for-close-confirmation.patch broken on 126
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

126.0.6478.55

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

The Close Confirmation flag added in "add-flag-for-close-confirmation.patch" is broken on chrome v126.

### How to Reproduce?

1. do a fresh install of ungoogled-chromium (I used https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/126.0.6478.55-1 and extracted it into an empty VM)
2. go to chrome://flags and set the "Close Confirmation" flag to "show confirmation with multiple windows"
3. click the "relaunch" prompt that shows up
4. after the browser relaunches, use the app menu (3 dots) -> new window
5. close the newly opened window
6. click either the "close" button or the "cancel" button

### Actual behaviour

The browser crashes and all windows closes, regardless of which option I choose.

### Expected behaviour

Only the window I want closed closes, or nothing happens if I click the "cancel" button.

### Relevant log output

```sh
[1744:148:0617/141300.903:WARNING:chrome_main_delegate.cc(742)] This is Chrome version 126.0.6478.55 (not a warning)
[1744:148:0617/141300.903:VERBOSE1:variations_field_trial_creator_base.cc(77)] VariationsSeedUsage:12
[1744:148:0617/141300.903:VERBOSE1:variations_field_trial_creator_base.cc(350)] VariationsSetupComplete
[1744:148:0617/141300.919:VERBOSE1:webrtc_event_log_manager.cc(97)] WebRTC remote-bound event logging enabled.
[1744:148:0617/141300.919:VERBOSE1:pref_proxy_config_tracker_impl.cc(191)] 0000700000044580: set chrome proxy config service to 0000700000118340
[1744:148:0617/141300.934:VERBOSE1:device_event_log_impl.cc(198)] [14:13:00.923] Display: EVENT: screen_win.cc:836 Displays updated, count: 1
[1744:148:0617/141300.934:VERBOSE1:device_event_log_impl.cc(198)] [14:13:00.927] Display: EVENT: screen_win.cc:838 Display[4957497] bounds=[0,0 2358x1298], workarea=[0,0 2358x1258], scale=1, rotation=0, panel_rotation=0 external detected
[1744:7048:0617/141300.934:VERBOSE1:media_stream_manager.cc(1527)] MSM::InitializeMaybeAsync([this=00007000000BAC00])
[1744:7048:0617/141300.934:VERBOSE1:media_stream_manager.cc(1527)] MDM::MediaDevicesManager()
[1744:7048:0617/141300.934:VERBOSE1:media_stream_manager.cc(1527)] MSM::MediaStreamManager([this=00007000000BAC00]))
[1744:1752:0617/141300.934:WARNING:dns_config_service_win.cc(605)] Failed to read DnsConfig.
[1744:148:0617/141300.934:VERBOSE1:chrome_browser_cloud_management_controller.cc(161)] Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[1744:148:0617/141300.934:VERBOSE1:install_util.cc(218)] No existing Chrome install found.
[1744:148:0617/141300.950:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:148:0617/141300.950:VERBOSE1:device_event_log_impl.cc(198)] [14:13:00.940] Bluetooth: EVENT: bluetooth_api.cc:82 BluetoothAPI: 000070000061DA00
[1744:148:0617/141300.950:VERBOSE1:pref_proxy_config_tracker_impl.cc(191)] 00007000000479C0: set chrome proxy config service to 000070000011AF20
[1744:148:0617/141300.950:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:148:0617/141300.950:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(223)] MutablePO2TS::MutablePO2TS
[1744:148:0617/141300.950:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:148:0617/141300.950:VERBOSE1:gaia_auth_util.cc(51)] Canonicalized @9ma1l.qjz9zk to @9ma1l.qjz9zk
[1744:148:0617/141300.950:VERBOSE1:gaia_auth_util.cc(51)] Canonicalized @9ma1l.qjz9zk to @9ma1l.qjz9zk
[1744:148:0617/141300.950:VERBOSE1:bluetooth_low_energy_event_router.cc(279)] Initializing BluetoothLowEnergyEventRouter.
[1744:148:0617/141300.950:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:148:0617/141300.950:VERBOSE1:account_reconcilor.cc(171)] AccountReconcilor::AccountReconcilor
[1744:148:0617/141300.950:VERBOSE1:account_reconcilor.cc(205)] AccountReconcilor::Initialize
[1744:148:0617/141300.950:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:148:0617/141300.950:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:1368:0617/141300.950:VERBOSE1:token_service_table.cc(148)] Loaded tokens: result = 3 ; number of tokens loaded = 0
[1744:148:0617/141300.950:VERBOSE1:gaia_auth_util.cc(51)] Canonicalized @9ma1l.qjz9zk to @9ma1l.qjz9zk
[1744:148:0617/141300.950:VERBOSE1:gaia_auth_util.cc(51)] Canonicalized @9ma1l.qjz9zk to @9ma1l.qjz9zk
[1744:148:0617/141300.965:VERBOSE1:extension_service.cc(1473)] AddComponentExtension Chromium PDF Viewer
[1744:148:0617/141300.965:WARNING:browser_management_service.cc(128)] EnterpriseLogoUrl fetch failed with error code -1 and MIME type 
[1744:148:0617/141300.965:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141300.965:VERBOSE1:profile_manager.cc(1982)] ForceSigninCheck: 0, 0, 1
[1744:2852:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Widevine Content Decryption Module
[1744:5456:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Subresource Filter Rules
[1744:148:0617/141300.965:VERBOSE1:on_device_head_suggest_component_installer.cc(61)] On Device Head Component will fetch model for locale: ENUS500000
[1744:1752:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for OnDeviceHeadSuggest
[1744:148:0617/141300.965:VERBOSE1:trust_token_key_commitments_component_installer.cc(30)] Registering Trust Token Key Commitments component.
[1744:1368:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Optimization Hints
[1744:148:0617/141300.965:VERBOSE1:first_party_sets_component_installer.cc(39)] Registering Related Website Sets component.
[1744:2628:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Trust Token Key Commitments
[1744:148:0617/141300.965:VERBOSE1:privacy_sandbox_attestations_component_installer.cc(207)] Registering Privacy Sandbox Attestations component
[1744:2620:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Privacy Sandbox Attestations
[1744:148:0617/141300.965:VERBOSE1:file_type_policies_component_installer.cc(114)] Registering File Type Policies component.
[1744:6704:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Certificate Error Assistant
[1744:5456:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for File Type Policies
[1744:6352:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for CRLSet
[1744:1368:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Origin Trials
[1744:1752:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for MEI Preload
[1744:2852:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for PKI Metadata
[1744:148:0617/141300.965:VERBOSE1:hyphenation_component_installer.cc(152)] Registering Hyphenation component.
[1744:6376:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Crowd Deny
[1744:2628:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Safety Tips
[1744:2620:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Hyphenation
[1744:6364:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Zxcvbn Data Dictionaries
[1744:148:0617/141300.965:VERBOSE1:tpcd_metadata_component_installer.cc(23)] Third Party Cookie Deprecation Metadata component.
[1744:6384:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Autofill States Data
[1744:6704:0617/141300.965:VERBOSE1:component_installer.cc(455)] StartRegistration for Third-Party Cookie Deprecation Metadata
[1744:148:0617/141300.965:VERBOSE1:profile_manager.cc(1324)] AddKeepAlive(Default, kBrowserWindow). keep_alives=[kWaitingForFirstBrowserWindow (1), kBrowserWindow (1)]
[1744:148:0617/141300.965:VERBOSE1:profile_manager.cc(1397)] ClearFirstBrowserWindowKeepAlive(Default). keep_alives=[kBrowserWindow (1)]
[1744:5456:0617/141300.965:VERBOSE1:command_storage_backend.cc(602)] CommandStorageBackend::ReadLastSessionCommands, reading commands from: C:\Users\Administrator\AppData\Local\Chromium\User Data\Default
[1744:6064:0617/141300.965:VERBOSE1:command_storage_backend.cc(602)] CommandStorageBackend::ReadLastSessionCommands, reading commands from: C:\Users\Administrator\AppData\Local\Chromium\User Data\Default\Sessions\Session_13363121483596350
[1744:148:0617/141300.965:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(407)] MutablePO2TS::OnWebDataServiceRequestDone. Result type: 6
[1744:148:0617/141300.965:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(464)] MutablePO2TS::LoadAllCredentialsIntoMemory; 0 redential(s).
[1744:148:0617/141300.965:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141300.965:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141300.965:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141300.965:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141300.965:WARNING:external_registry_loader_win.cc(232)] Error observing HKLM: 5
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Subresource Filter Rules
[1744:148:0617/141300.965:VERBOSE1:component_updater_service.cc(163)] CrxUpdateService starting up. First update attempt will take place in 60 s seconds. Next update attempt will take place in 18000 s seconds. 
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Widevine Content Decryption Module
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for OnDeviceHeadSuggest
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Optimization Hints
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Trust Token Key Commitments
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Privacy Sandbox Attestations
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Certificate Error Assistant
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for File Type Policies
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Crowd Deny
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Origin Trials
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Safety Tips
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for PKI Metadata
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Third-Party Cookie Deprecation Metadata
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for CRLSet
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Autofill States Data
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Zxcvbn Data Dictionaries
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for MEI Preload
[1744:148:0617/141300.965:VERBOSE1:component_installer.cc(534)] FinishRegistration for Hyphenation
[1336:6348:0617/141300.965:WARNING:dns_config_service_win.cc(605)] Failed to read DnsConfig.
[1744:148:0617/141300.981:VERBOSE1:profile_manager.cc(1324)] AddKeepAlive(Default, kBrowserWindow). keep_alives=[kBrowserWindow (2)]
[1744:5456:0617/141300.981:VERBOSE1:command_storage_backend.cc(602)] CommandStorageBackend::ReadLastSessionCommands, reading commands from: C:\Users\Administrator\AppData\Local\Chromium\User Data\Default\Sessions\Tabs_13363121483731903
[1336:6436:0617/141300.981:VERBOSE1:configured_proxy_resolution_service.cc(1162)] Failed configuring with PAC script, falling-back to manual proxy servers.
[1336:6436:0617/141300.981:VERBOSE1:configured_proxy_resolution_service.cc(1162)] Failed configuring with PAC script, falling-back to manual proxy servers.
[1744:148:0617/141301.012:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141301.012:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:148:0617/141301.028:VERBOSE1:device_event_log_impl.cc(198)] [14:13:01.014] Display: EVENT: screen_win.cc:836 Displays updated, count: 1
[1744:148:0617/141301.028:VERBOSE1:device_event_log_impl.cc(198)] [14:13:01.014] Display: EVENT: screen_win.cc:838 Display[4957497] bounds=[0,0 2358x1298], workarea=[0,0 2358x1258], scale=1, rotation=0, panel_rotation=0 external detected
[1744:148:0617/141301.043:VERBOSE1:profile_manager.cc(1324)] AddKeepAlive(Default, kBrowserWindow). keep_alives=[kBrowserWindow (3)]
[5436:5684:0617/141301.043:INFO:cpu_info.cc(53)] Available number of cores: 16
[5656:1828:0617/141301.043:INFO:cpu_info.cc(53)] Available number of cores: 16
[5436:5684:0617/141301.043:WARNING:runtime_features.cc(688)] AttributionReporting cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement in addition.
[5436:5684:0617/141301.043:WARNING:runtime_features.cc(702)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[5656:1828:0617/141301.043:WARNING:runtime_features.cc(688)] AttributionReporting cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement in addition.
[5656:1828:0617/141301.043:WARNING:runtime_features.cc(702)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[1744:148:0617/141301.059:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141301.059:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing Session.TotalDuration
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing Commerce.PriceDrops.ActiveTabNavigationComplete.IsProductDetailPage
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(54)] Segmentation platform started observing Autofill_PolledCreditCardSuggestions
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing Omnibox.SuggestionUsed.ClientSummarizedResultType
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing Sync.DeviceCount2
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing Sync.DeviceCount2.Phone
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing Sync.DeviceCount2.Desktop
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing Sync.DeviceCount2.Tablet
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(54)] Segmentation platform started observing MobileBookmarkManagerOpen
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(54)] Segmentation platform started observing NewTabPage.MostVisited.Clicked
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(54)] Segmentation platform started observing TabGroup.Created.OpenInNewTab
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(54)] Segmentation platform started observing Android.HistoryPage.OpenItem
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(54)] Segmentation platform started observing MobileMenuRecentTabs
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing PasswordManager.ManagePasswordsReferrer
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing PasswordManager.ProfileStore.TotalAccountsHiRes3.WithScheme.Https
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing PasswordManager.FillingAssistance
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing PasswordManager.NewlySavedPasswordIsGenerated
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing PasswordManager.SaveUIDismissalReason
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing PasswordManager.SaveUIDismissalReason
[1744:148:0617/141301.075:VERBOSE1:signal_filter_processor.cc(61)] Segmentation platform started observing IOS.CredentialExtension.IsEnabled.Startup
[3116:3120:0617/141301.130:INFO:cpu_info.cc(53)] Available number of cores: 16
[3116:3120:0617/141301.130:WARNING:runtime_features.cc(688)] AttributionReporting cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement in addition.
[3116:3120:0617/141301.130:WARNING:runtime_features.cc(702)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[1744:148:0617/141301.137:VERBOSE1:profile_manager.cc(1376)] RemoveKeepAlive(Default, kBrowserWindow). keep_alives=[kBrowserWindow (2)]
[1744:148:0617/141301.137:VERBOSE1:device_event_log_impl.cc(198)] [14:13:01.131] Display: EVENT: screen_win.cc:836 Displays updated, count: 1
[1744:148:0617/141301.137:VERBOSE1:device_event_log_impl.cc(198)] [14:13:01.131] Display: EVENT: screen_win.cc:838 Display[4957497] bounds=[0,0 2358x1298], workarea=[0,0 2358x1258], scale=1, rotation=0, panel_rotation=0 external detected
[5656:1828:0617/141301.153:VERBOSE1:script_context.cc(149)] Created context:
  extension id:           (none)
  frame:                  00004C4F0014E238
  URL:                    
  context_type:           WEBUI
  effective extension id: (none)
  effective context type: WEBUI
[3116:3120:0617/141301.153:VERBOSE1:script_context.cc(149)] Created context:
  extension id:           (none)
  frame:                  000074710014E238
  URL:                    
  context_type:           WEBUI
  effective extension id: (none)
  effective context type: WEBUI
[5656:1828:0617/141301.153:VERBOSE1:script_context.cc(149)] Created context:
  extension id:           (none)
  frame:                  0000000000000000
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[3116:3120:0617/141301.153:VERBOSE1:script_context.cc(149)] Created context:
  extension id:           (none)
  frame:                  0000000000000000
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[3116:3120:0617/141301.155:VERBOSE1:dispatcher.cc(419)] Num tracked contexts: 1
[5656:1828:0617/141301.155:VERBOSE1:dispatcher.cc(419)] Num tracked contexts: 1
[1744:148:0617/141301.156:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141301.158:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141301.288:VERBOSE1:segment_result_provider.cc(136)] GetSegmentResult: segment=OPTIMIZATION_TARGET_SEGMENTATION_DEVICE_SWITCHER ignoring DB score, executing model.
[1744:148:0617/141301.288:VERBOSE1:segment_result_provider.cc(277)] ExecuteModelAndGetScore: segment=OPTIMIZATION_TARGET_SEGMENTATION_DEVICE_SWITCHER default segment info not available
[1744:148:0617/141301.288:VERBOSE1:segment_result_provider.cc(210)] OnGotModelScore: segment=OPTIMIZATION_TARGET_SEGMENTATION_DEVICE_SWITCHER failed to get database model score, trying default model.
[1744:148:0617/141302.794:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141302.794:VERBOSE1:profile_manager.cc(1324)] AddKeepAlive(Default, kChromeViewsDelegate). keep_alives=[kBrowserWindow (2), kChromeViewsDelegate (1)]
[1744:4184:0617/141303.200:VERBOSE1:component_installer.cc(455)] StartRegistration for Related Website Sets
[1744:148:0617/141303.224:VERBOSE1:component_installer.cc(534)] FinishRegistration for Related Website Sets
[1744:148:0617/141303.224:VERBOSE1:first_party_sets_component_installer.cc(44)] Received Related Website Sets
[1744:148:0617/141303.226:VERBOSE1:profile_manager.cc(1324)] AddKeepAlive(Default, kExtensionUpdater). keep_alives=[kBrowserWindow (2), kChromeViewsDelegate (1), kExtensionUpdater (1)]
[1744:148:0617/141303.226:VERBOSE1:profile_manager.cc(1376)] RemoveKeepAlive(Default, kExtensionUpdater). keep_alives=[kBrowserWindow (2), kChromeViewsDelegate (1)]
[1744:148:0617/141303.229:VERBOSE1:device_event_log_impl.cc(198)] [14:13:03.216] USB: USER: usb_service_win.cc:762 USB device added: path=\\?\usb#vid_0e0f&pid_0003#6&30c5d09c&0&5#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=3599 "VMware", product=3 "VMware Virtual USB Mouse", serial="", driver="usbccgp", guid=fdf19afd-cfc5-40ff-92ea-d4ea230953a1
[1744:148:0617/141303.471:VERBOSE1:profile_manager.cc(1324)] AddKeepAlive(Default, kBrowserWindow). keep_alives=[kBrowserWindow (3), kChromeViewsDelegate (1)]
[1744:148:0617/141303.482:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
[1744:148:0617/141303.482:VERBOSE1:account_consistency_mode_manager.cc(206)] Desktop Identity Consistency disabled as sign-in to Chrome is not allowed
[2576:3152:0617/141303.513:INFO:cpu_info.cc(53)] Available number of cores: 16
[2576:3152:0617/141303.528:WARNING:runtime_features.cc(688)] AttributionReporting cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement in addition.
[2576:3152:0617/141303.528:WARNING:runtime_features.cc(702)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[1744:148:0617/141303.528:VERBOSE1:profile_manager.cc(1376)] RemoveKeepAlive(Default, kChromeViewsDelegate). keep_alives=[kBrowserWindow (3)]
[5436:5684:0617/141303.528:VERBOSE1:script_context.cc(149)] Created context:
  extension id:           (none)
  frame:                  00003E5B0014E238
  URL:                    
  context_type:           WEBUI
  effective extension id: (none)
  effective context type: WEBUI
[5436:5684:0617/141303.528:VERBOSE1:script_context.cc(149)] Created context:
  extension id:           (none)
  frame:                  0000000000000000
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[5436:5684:0617/141303.528:VERBOSE1:dispatcher.cc(419)] Num tracked contexts: 1
[1744:148:0617/141303.543:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(310)] MutablePO2TS::RefreshTokenIsAvailable
```

### Additional context

This seems to be tied to the prompt itself. If I choose the "show confirmation with last window" option, windows close fine until the last one (when the prompt shows up).

### PR DESCRIPTION
**Pull request by Nifury**
Fixes #2917

### CODE REVIEW

**Review by Ahrotahn — APPROVED** [review]
Works fine in my build, thanks @Nifury!

**Comment by rany2** [comment]
Is it worth it to release a -2 for this?

**Review by networkException — APPROVED** [review]
Looks good, less crashes from my testing :)

**Comment by networkException** [comment]
@Nifury It looks like I can't get the ssh public key you used to sign the commit with from GitHub (https://github.com/Nifury.keys), I usually like to configure my git client to just TOFU verify everything

**Comment by Nifury** [comment]
> It looks like I can't get the ssh public key you used to sign the commit with from GitHub

I don't really understand why the link doesn't work. Is it because I only configured SSH signing key?

This is the only link I can find that retrieves my public key: https://api.github.com/users/nifury/ssh_signing_keys

**Comment by networkException** [comment]
Interesting, oh well :D

**Pull request merged**
