### PR TITLE
Update to Chromium 109.0.5414.74/75/87

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 109.0.5414.74/75/87.

Notable changes:

* The fix-building-with-prunned-binaries patch has been updated for the changes in [[4000481]](https://chromium-review.googlesource.com/c/chromium/src/+/4000481) and a removal was added for [[4020853]](https://chromium-review.googlesource.com/c/chromium/src/+/4020853).
* remove-unused-preferences-fields had some changes moved around due to [[3922658]](https://chromium-review.googlesource.com/c/chromium/src/+/3922658) and some new additions for [[39449955]](https://chromium-review.googlesource.com/c/chromium/src/+/3944995).
* The safebrowsing patch had some changes due to [[3934399]](https://chromium-review.googlesource.com/c/chromium/src/+/3934399).
* A small change in disable-download-quarantine.patch to have GetEffectiveAuthorityURL return the source url to handle the changes in [[4016873]](https://chromium-review.googlesource.com/c/chromium/src/+/4016873) and any future uses.

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/108.0.5359.125..109.0.5414.87?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2023/01/stable-channel-update-for-desktop.html)

### CODE REVIEW

**Comment by macchrome** [comment]
Is drag and drop working?

I've done a preliminary Windows build and drag and drop is not working and am aware of  chrome://flags/#disable-link-drag

**Comment by Ahrotahn** [comment]
Good catch, I forgot to replace the drop callback with the changes to the safebrowsing patch.

**Comment by PF4Public** [comment]
Builds and runs 👍🏻

**Review by networkException — APPROVED** [review]
Builds and runs (the linux release)

**Comment by PF4Public** [comment]
@macchrome If you're distributing binaries with Bromite patches applied, but do not provide full sources accompanied by building scripts, you might be in violation of the GPL. Just sayin'.

**Review by PF4Public — APPROVED** [review]

**Comment by networkException** [comment]
How do you feel about merging this already?

**Comment by PF4Public** [comment]
It is a pity we cannot test Windows builds before merging core repo :( But from Linux perspective everything seems to be OK. Well, I got [1 issue report](https://github.com/PF4Public/gentoo-overlay/issues/197) in my repo, but I suspect it might be a heisenbug from upstream.

**Comment by teeminus** [comment]
I have already updated the windows patches for the new release. But I have not yet pushed them because the patches require the submodule to be updated as well.

**Comment by PF4Public** [comment]
@teeminus Have you attempted building yet?

**Comment by teeminus** [comment]
Of course :-) Builds and runs fine.

**Comment by PF4Public** [comment]
> Of course :-) Builds and runs fine.

I stand corrected :) We are good on Linux and Windows :)

**Comment by Rusenche** [comment]
I found a bug which is presented here. I clearly show: 
error

**Comment by networkException** [comment]
ah crap, I really need to automate this

sadly tag descriptions can't be updated easily

**Comment by PF4Public** [comment]
> sadly tag descriptions can't be updated easily

Then maybe do not add any text into tags? Do it in releases instead? There is an [API that might be handy in automation](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release).

**Comment by 0xfedcafe** [comment]
> > Of course :-) Builds and runs fine.
> 
> I stand corrected :) We are good on Linux and Windows :)

just wanted to notice that on gentoo using your ebuild ungoogled-chromium-bin I received error "chromium-browser: error while loading shared libraries: libre2.so.9: cannot open shared object file: No such file or directory" and the solution is "ln -s /usr/lib64/libre2.so /usr/lib64/libre2.so.9"

**Pull request merged**
