### PR TITLE
Update to Chromium 116.0.5845.110/111

### PR DESCRIPTION
**Pull request by PF4Public**
There were changes in [e8d22824be3aebcf319e0debabd37967e6075d11](https://source.chromium.org/chromium/chromium/src/+/e8d22824be3aebcf319e0debabd37967e6075d11), therefore I suggest waiting for at least one successful build _and_ run before merging (just to be sure I didn't break anything).

### CODE REVIEW

**Comment by PF4Public** [comment]
I missed one code block, which resulted in following error:

```sh
./../components/safe_browsing/core/browser/db/v4_local_database_manager.cc:704:9: error: unknown type name 'record_migration_metrics_callback_'; did you mean 'RecordMigrationMetricsCallback'?
  704 |     if (record_migration_metrics_callback_) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         RecordMigrationMetricsCallback
../../components/safe_browsing/core/browser/db/v4_local_database_manager.h:37:9: note: 'RecordMigrationMetricsCallback' declared here
   37 |   using RecordMigrationMetricsCallback =
      |         ^
../../components/safe_browsing/core/browser/db/v4_local_database_manager.cc:704:43: error: expected unqualified-id
  704 |     if (record_migration_metrics_callback_) {
      |                                           ^
../../components/safe_browsing/core/browser/db/v4_local_database_manager.cc:707:36: error: use of undeclared identifier 'record_migration_metrics_callback_'
  707 |           base::BindOnce(std::move(record_migration_metrics_callback_),
      |                                    ^
3 errors generated.
```

Still haven't finished building.

**Comment by madscientist159** [comment]
With the update just prior, build checks pass on my end...

**Comment by PF4Public** [comment]
> With the update just prior, build checks pass on my end...

Does it build?

**Comment by madscientist159** [comment]
> > With the update just prior, build checks pass on my end...
> 
> Does it build?

Yes, it builds.  Sorry I wasn't clear :smile:

**Comment by PF4Public** [comment]
With latest changes builds and runs on Linux for me.

**Review by networkException — APPROVED** [review]

**Comment by networkException** [comment]
Builds and runs for me as well, I'd admin merge this if no complaints arise in the next few hours

**Pull request merged**
