### PR TITLE
Misc development improvements

### PR DESCRIPTION
**Pull request by networkException**
Very me setup specific but it might be helpful to others as well

### CODE REVIEW

**Review by Ahrotahn — APPROVED** [review]
Seems fine to me!

**Comment by PF4Public** [comment]
What is the purpose of `shell.nix`?

**Comment by networkException** [comment]
`shell.nix` makes the listed packages available in the current shell when running a command to activate them. Basically it makes working on various projects easy without having to install all of their build dependencies globally

**Comment by PF4Public** [comment]
Since it is very nix specific, is there possibility to have this file be present locally but outside version control via gitignore for example?

**Comment by networkException** [comment]
Yea its pretty nix specific, it would be quite nice though to have it upstream as a machine readable definition of the development dependencies

**Comment by PF4Public** [comment]
> it would be quite nice though to have it upstream

Well, if you say so :)

**Review by PF4Public — APPROVED** [review]

**Comment by Ahrotahn** [comment]
@networkException Do you mind rebasing this, or is a merge commit alright?

**Comment by networkException** [comment]
eeh

**Pull request merged**
