### PR TITLE
Update to Chromium 123.0.6312.58

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 123.0.6312.58

Notes:

* The crash reporter patch had some changes due to [[5237441]](https://chromium-review.googlesource.com/c/chromium/src/+/5237441)

* The safebrowsing patch had new additions for [[5160892]](https://chromium-review.googlesource.com/c/chromium/src/+/5160892), [[5246599]](https://chromium-review.googlesource.com/c/chromium/src/+/5246599), [[5297235]](https://chromium-review.googlesource.com/c/chromium/src/+/5297235), and [[5301128]](https://chromium-review.googlesource.com/c/chromium/src/+/5301128) which should have been gated on enterprise_client_certificates.  There was also a removal for [[5274127]](https://chromium-review.googlesource.com/c/chromium/src/+/5274127).

* remove-unused-preferences-fields.patch had a removal for [[5160892]](https://chromium-review.googlesource.com/c/chromium/src/+/5160892)

* The fix-building-with-prunned-binaries patch had some changes due to [[5315923]](https://chromium-review.googlesource.com/c/chromium/src/+/5315923).  The headers were gated but the code that uses them wasn't, ironically causing it not to build.  There were also new additions for screen-ai in [[5314624]](https://chromium-review.googlesource.com/c/chromium/src/+/5314624).

* I've added logging to the pruning script for the removal of the contingent paths.  This should hopefully let us know if there are any issues with the paths going forward.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/122.0.6261.128..123.0.6312.58?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/03/stable-channel-update-for-desktop_19.html)

### CODE REVIEW

**Comment by teeminus** [comment]
Seems like you can't generate QrCodes without rust anymore. Or am I wrong?

The previous patch did not apply because there was a lot of code removed from the `qr_code_generator.cc`.

**Comment by teeminus** [comment]
Seems like there are way more rust dependencies than before:

```
ERROR Unresolved dependencies.
//build/rust/chromium_prelude:chromium_prelude(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//build/rust/chromium_prelude:chromium_prelude(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//build/rust/chromium_prelude:import_attribute(//build/toolchain/win:win_clang_x64)
  needs //build/rust/chromium_prelude:import_attribute__proc_macro(//build/toolchain/win:win_clang_x64_for_rust_host_build_tools)
//build/rust/chromium_prelude:import_test(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//build/rust/chromium_prelude:import_test(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//build/rust/chromium_prelude:import_test_lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//build/rust/chromium_prelude:import_test_lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/cbor:cbor(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/cbor:cbor(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/chromesync:chromesync(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/chromesync:chromesync(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/crypto:crypto(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/crypto:crypto(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/crypto:crypto(//build/toolchain/win:win_clang_x64)
  needs //third_party/boringssl:bssl_crypto(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/handshake:handshake(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/handshake:handshake(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/processor:processor(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/processor:processor(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/test/local_service:cloud_authenticator_test_service(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//third_party/cloud_authenticator/test/local_service:cloud_authenticator_test_service(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/rust/base64/v0_13:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2018(//build/toolchain/win:win_clang_x64)
//third_party/rust/base64/v0_13:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/rust/bytes/v1:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2018(//build/toolchain/win:win_clang_x64)
//third_party/rust/bytes/v1:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/rust/hex/v0_4:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2018(//build/toolchain/win:win_clang_x64)
//third_party/rust/hex/v0_4:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/rust/lazy_static/v1:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2015(//build/toolchain/win:win_clang_x64)
//third_party/rust/lazy_static/v1:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/rust/prost/v0_12:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2021(//build/toolchain/win:win_clang_x64)
//third_party/rust/prost/v0_12:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
//third_party/rust/prost_derive/v0_12:lib(//build/toolchain/win:win_clang_x64)
  needs //third_party/rust/prost_derive/v0_12:lib__proc_macro(//build/toolchain/win:win_clang_x64_for_rust_host_build_tools)
//third_party/rust/static_assertions/v1:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust:edition_2015(//build/toolchain/win:win_clang_x64)
//third_party/rust/static_assertions/v1:lib(//build/toolchain/win:win_clang_x64)
  needs //build/rust/std:std(//build/toolchain/win:win_clang_x64)
```

**Comment by Ahrotahn** [comment]
Yes, they've removed the c++ code in [[5091218]](https://chromium-review.googlesource.com/c/chromium/src/+/5091218).  I thought they had already already made the change last version but I guess it got pushed back.

**Comment by clickot** [comment]
builds and runs fine with portablellinux build and ubuntu 20.04 and above

**Review by networkException — APPROVED** [review]

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
