### PR TITLE
Update to Chromium 130.0.6723.58

### LINKED ISSUE #1130: Remove Sync (ie: "Not Signed In", "Turn on sync...", "Sync and Google services", etc) UI
**Is your feature request related to a problem? Please describe.**

This isn't really a problem so much as that the UI is showing options for and suggesting the use of sync functionality which has been disabled.

**Describe the solution you'd like**

The package would feel much more complete if the account dropdown didn't have a broken sync icon, the message `Not signed in` and a big `Turn on sync` bubble. The `Sync and Google Services` menu and other settings that require being signed into a google account in the settings are much less in your face but is also a bit redundant.

**Describe alternatives you've considered**

I'm not sure if there's really an alternative way to remove something, but the dialogs in the account dropdown are definitely the most jarring.

**Additional context**

redundant-sync-dropdown

redundant-sync-setup

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 130.0.6723.58

Notes:

* A new binary exclusion has been added for bindings_wasm_bg.wasm which was added in [#5073](https://www.github.com/rollup/rollup/pull/5073) for version 4.0 of rollup.  This is included in the node_modules download so I'm not sure if there is a better means of handling that.  

* The doh-changes patch had a section moved to a new area in [[5546423]](https://chromium-review.googlesource.com/c/chromium/src/+/5546423)

* The safebrowsing patch had changes for [[5791595]](https://chromium-review.googlesource.com/c/chromium/src/+/5791595)

* remove-unused-preferences-fields.patch had changes for [[5823396]](https://chromium-review.googlesource.com/c/chromium/src/+/5823396)

* The MDNS patch had a new addition for [[5828629]](https://chromium-review.googlesource.com/c/chromium/src/+/5828629).  For some reason they added the the dep twice and only gated the second instance.  

* remove-uneeded-ui.patch had a removal for [[5855283]](https://chromium-review.googlesource.com/c/chromium/src/+/5855283) and a small change to an existing section to fix #1130.  

* A new patch has been added to the upstream fixes directory.  They introduced new changes in [[5767325]](https://chromium-review.googlesource.com/c/chromium/src/+/5767325) using `std::hardware_destructive_interference_size` which requires a newer version of LLVM and then partially reverted the change in [[5841144]](https://chromium-review.googlesource.com/c/chromium/src/+/5841144).  The new patch reverts the remaining change.  

* A new addition to the missing dependencies patch for a usage of `base::Contains` that no longer has the include supplied transitively.  Their own code browser isn't able to find a reference so I'm not sure how that is building for them.  

* The change in [[5850578]](https://chromium-review.googlesource.com/c/chromium/src/+/5850578) causes implicit conversion warnings.  If the spam causes problems for your build then `-Wno-shorten-64-to-32` might be necessary.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/129.0.6668.100..130.0.6723.58?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/10/stable-channel-update-for-desktop_15.html)

### CODE REVIEW

**Comment by Ahrotahn** [comment]
I've pushed an update to `add-flag-to-close-window-with-last-tab.patch` moving the new tab creation ahead of the reentrancy checks.  They started enforcing those with 130.  

<hr>

Also there's a fix for the GBM log spam when playing videos on wayland in [[5873796]](https://chromium-review.googlesource.com/c/chromium/src/+/5873796).  It probably won't land until 131, but applies cleanly on 130.

**Comment by clickot** [comment]
portable linux builds and runs fine

**Comment by teeminus** [comment]
.44 builds and runs fine on windows as well.

**Comment by clickot** [comment]
404 on chromium-130.0.6723.58.tar.xz download. Not yet published?

**Comment by Ahrotahn** [comment]
The tarball for .58 is not yet available since their builder seems to be having issues at the moment:  https://ci.chromium.org/ui/p/infra/builders/cron/publish_tarball

I'm not sure how long until that gets resolved, so I guess this is only really ready for clones at the moment.

**Comment by PF4Public** [comment]
Should we be waiting for a tarball?

**Comment by Ahrotahn** [comment]
The tarball is available now.  
Hopefully they can get that cleared up before next week...

**Review by networkException — APPROVED** [review]

**Comment by clickot** [comment]
.58 builds and runs fine on portable linux

**Comment by Cubik65536** [comment]
Builds fine on macOS (Apple Silicon).

**Comment by PF4Public** [comment]
```diff
-                                         net::SecureDnsMode::kAutomatic)));
+                                         net::SecureDnsMode::kOff)));
```
Are we setting it to "off" because it'll try to connect google servers in "automatic"?

**Comment by Ahrotahn** [comment]
The Google servers are also removed in that patch so it shouldn't use them by default.  I think the setting was disabled by default due to the patch allowing DoH to work on linux back when that wasn't supported upstream and we didn't want to override the system configuration.  

We could remove that now that most people are aware of the setting.  Although I've still seen some people surprised to find that bypasses their Pi-hole setup or can route their traffic to Cloudflare for example.

**Comment by PF4Public** [comment]
Well, it should be safer with "off" then

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
