### PR TITLE
Update to Chromium 120.0.6099.71

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 120.0.6099.71.

Notes:

* A minor change in the trk patch due to [[4944854]](https://chromium-review.googlesource.com/c/chromium/src/+/4944854)

* The pruned binary patch had a removal for [[4939797]](https://chromium-review.googlesource.com/c/chromium/src/+/4939797) and new additions for [[4907777]](https://chromium-review.googlesource.com/c/chromium/src/+/4907777)

* New additions to the safebrowsing patch for [[4913553]](https://chromium-review.googlesource.com/c/chromium/src/+/4913553) and [[4955836]](https://chromium-review.googlesource.com/c/chromium/src/+/4955836)

* remove-unused-preferences-fields.patch had changes due to [[4936174]](https://chromium-review.googlesource.com/c/chromium/src/+/4936174), [[4957138]](https://chromium-review.googlesource.com/c/chromium/src/+/4957138), [[4956319]](https://chromium-review.googlesource.com/c/chromium/src/+/4956319)

* The version check in the prepopulated search engine patch has been removed now that [[4915859]](https://chromium-review.googlesource.com/c/chromium/src/+/4915859) has been merged

* Adjustments to the remove ui patch for [[4912694]](https://chromium-review.googlesource.com/c/chromium/src/+/4912694) and [[4935577]](https://chromium-review.googlesource.com/c/chromium/src/+/4935577)

* The clone script has been updated to remove empty directories that were causing gsync to error out when updating existing clones

* If you are building with an earlier version of clang then the flag changes in [[4903785]](https://chromium-review.googlesource.com/c/chromium/src/+/4903785) may need to be reverted

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/119.0.6045.199..120.0.6099.71?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2023/12/stable-channel-update-for-desktop.html) / [Blog post](https://chromereleases.googleblog.com/2023/12/stable-channel-update-for-desktop_6.html)

### CODE REVIEW

**Comment by teeminus** [comment]
Linking for windows failed:
```
lld-link: error: undefined symbol: public: static class AutocompleteScoringModelServiceFactory * __cdecl AutocompleteScoringModelServiceFactory::GetInstance(void)
>>> referenced by ../../chrome/browser/ui/webui/omnibox/omnibox_page_handler.cc
>>>               obj/chrome/browser/ui\ui/omnibox_page_handler.obj

lld-link: error: undefined symbol: public: static class AutocompleteScoringModelService * __cdecl AutocompleteScoringModelServiceFactory::GetForProfile(class Profile *)
>>> referenced by ../../chrome/browser/ui/webui/omnibox/omnibox_page_handler.cc
>>>               obj/chrome/browser/ui\ui/omnibox_page_handler.obj
```

I fixed it with the following patch (but I don't know if it's the correct way to fix the error):
```
@@ -549,8 +529,5 @@ OmniboxPageHandler::GetAutocompleteControllerType(
 }

 AutocompleteScoringModelService* OmniboxPageHandler::GetMlService() {
-  return OmniboxFieldTrial::IsMlSyncBatchUrlScoringEnabled()
-             ? AutocompleteScoringModelServiceFactory::GetInstance()
-                   ->GetForProfile(profile_)
-             : nullptr;
+  return nullptr;
 }
```

**Comment by PF4Public** [comment]
>Only snyc the prepoulated

Funny typo that no one noticed before :D

**Comment by PF4Public** [comment]
They finally made it impossible to build with `use_custom_libcxx=false` :(

**Comment by networkException** [comment]
There's no tarball for .71 yet sadly

**Review by networkException — APPROVED** [review]

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
