### PR TITLE
Fix broken link in readme

### PR DESCRIPTION
**Pull request by kwarabei**

### CODE REVIEW

**Comment by networkException** [comment]
I honestly don't know why these weird urls without a scheme are everywhere

**Review by networkException — DISMISSED** [review]

**Comment by PF4Public** [comment]
Is this an error? I was thinking that omitting the scheme does not make an URL invalid, browser should use the existing scheme on the URL you are already on, shouldn't it?

**Comment by tomasz1986** [comment]
> Is this an error? I was thinking that omitting the scheme does not make an URL invalid, browser should use the same scheme as on the URL you are already on, shouldn't it?

This is true in technical terms, but as far as I know, the best practice nowadays is to hard-code the scheme whenever possible, and specifically use `https:` when available (as otherwise the browser may navigate to `http:` even if `https:` is available.

**Comment by Ahrotahn** [comment]
I think the change is fine since most sites have gone https-only by now.  There isn't much reason to use scheme-relative URLs these days.  

With that said, if we're changing that we should also change all of the other URLs.  The same pattern is used for other links in README.md, SUPPORT.md, devutils/third_party/README.md, docs/design.md, docs/developing.md, docs/platforms.md, docs/repo_management.md, and utils/third_party/README.md

**Comment by networkException** [comment]
Nice, I just briefly looked up the URL spec and couldn't find anything relating to this. Could have figured that user agents are supposed to special case this

**Comment by PF4Public** [comment]
> With that said, if we're changing that we should also change all of the other URLs.

My thought exactly.

**Comment by PF4Public** [comment]
@kwarabei Would you be able to hunt down all the scheme-relative URLs in docs and convert them to proper https URLs? (since you started this :) )

**Comment by kwarabei** [comment]
@PF4Public Yes, I will look for them at the weekend and update this PR

**Comment by PF4Public** [comment]
@kwarabei You seem to have changed indentation a number of times and replaced some formatting symbols. Is it intentional?

**Comment by kwarabei** [comment]
@PF4Public No, my text editor applied some autoformatting on save. `.md` and `.yml` files seem to be properly rendered though. If these changes in indentation and  characters are inappropriate I will bring them to the initial state.

**Comment by networkException** [comment]
Well not necessarily inappropriate, just a bit out of scope. I wouldn't mind merging this as is though

**Comment by PF4Public** [comment]
I think that a commit trying to fix a link should do just that, otherwise its purpose might be misleading and raise unnecessary doubts. Touching the code besides the links might blur the idea behind the fix.

Apart from that I remember struggling with GitHub as YAML is very indentation-sensitive. So I'd suggest not fixing what is functioning.

**Comment by Ahrotahn** [comment]
I don't see that being a problem for the documentation, but I think it would be best not to make those extra changes in the template files.  

There's still a handful of places that would need to be updated as well:
<details><summary><code>rg "\(//"</code></summary>

```
README.md
61:    * This includes disabling [Safe Browsing](//en.wikipedia.org/wiki/Google_Safe_Browsing). Consult [the FAQ for the rationale](//ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-is-safe-browsing-disabled).
86:* [Inox patchset](//github.com/gcarq/inox-patchset)
87:* [Bromite](//github.com/bromite/bromite)
88:* [Debian](//tracker.debian.org/pkg/chromium-browser)
89:* [Iridium Browser](//iridiumbrowser.de/)
104:* Arch: Available in AUR & OBS, [see instructions in ungoogled-chromium-archlinux](//github.com/ungoogled-software/ungoogled-chromium-archlinux)
105:* Debian & Ubuntu: Available in OBS, find your [distribution specific instructions](//github.com/ungoogled-software/ungoogled-chromium-debian) in the Installing section
106:* Fedora: Available in OBS, by following [instructions](//github.com/ungoogled-software/ungoogled-chromium-fedora) in the downloads section. Also available in [RPM Fusion](https://rpmfusion.org/Configuration) as `chromium-browser-privacy` (outdated).
130:If you wish to include ungoogled-chromium code in your own build process, consider using [the tags in this repo](//github.com/ungoogled-software/ungoogled-chromium/tags). These tags follow the format `{chromium_version}-{revision}` where
147:[See the frequently-asked questions (FAQ) on the Wiki](//ungoogled-software.github.io/ungoogled-chromium-wiki/faq)
160:* If you're willing to help, check out the [Issue Tracker](//github.com/ungoogled-software/ungoogled-chromium/issues) and especially issues, which [need help](//github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
166:* [The Chromium Project](//www.chromium.org/)
167:* [Inox patchset](//github.com/gcarq/inox-patchset)
168:* [Debian](//tracker.debian.org/pkg/chromium-browser)
169:* [Bromite](//github.com/bromite/bromite)
170:* [Iridium Browser](//iridiumbrowser.de/)
171:* The users for testing and debugging, [contributing code](//github.com/ungoogled-software/ungoogled-chromium/graphs/contributors), providing feedback, or simply using ungoogled-chromium in some capacity.
177:* [Bromite](//github.com/bromite/bromite) (Borrows some patches. Features builds for Android)
178:* [ppc64le fork](//github.com/leo-lb/ungoogled-chromium) (Fork with changes to build for ppc64le CPUs)

devutils/third_party/README.md
5:* [python-unidiff](//github.com/matiasb/python-unidiff)

docs/developing.md
5:Information targeted towards developers *and* other users live in [the Wiki](//ungoogled-software.github.io/ungoogled-chromium-wiki/).

docs/design.md
92:    * Patches are from [inox-patchset's GitHub](//github.com/gcarq/inox-patchset)
93:    * [Inox patchset's license](//github.com/gcarq/inox-patchset/blob/master/LICENSE)
94:* `bromite/` - Patches from [Bromite](//github.com/bromite/bromite)
98:    * Patches are from the `patchview` branch of Iridium's Git repository. [Git webview of the patchview branch](//git.iridiumbrowser.de/cgit.cgi/iridium-browser/?h=patchview)
107:Packaging files use the code from this repository to build ungoogled-chromium. Each platform and configuration has an associated packaging repository under the [ungoogled-software](//github.com/ungoogled-software) organization. For more information about each packaging repository, see the [building documentation](building.md).
```
</details>

**Comment by kwarabei** [comment]
I added https prefixes, but indentation in YML was left intact this time.

**Review by networkException — APPROVED** [review]

**Review by PF4Public — APPROVED** [review]

**Comment by PF4Public** [comment]
Thanks!

**Pull request merged**
