### PR TITLE
Upstream extension-search-path.patch

### PR DESCRIPTION
**Pull request by Pandapip1**
Upstreams the extension search path patch from https://github.com/NixOS/nixpkgs/pull/188086

### CODE REVIEW

**Review by PF4Public — CHANGES_REQUESTED** [review]
Same considerations as voiced in nix issue tracker.

Besides, this patch does not apply.

**Comment by networkException** [comment]
I avoided the nixpkgs issue largely because of its slightly convoluted history.

Given that I both maintain ungoogled-chromium and it's nixpkgs packaging (CC @emilylange), I'll try to take a closer look (can't promise when) at declarative extensions and whether ungoogled-chromium should put patches for it into its patchset

**Comment by Pandapip1** [comment]
> Besides, this patch does not apply.

One of the stated goals of the `ungoogled-chromium` project is:

> ungoogled-chromium features tweaks to enhance privacy, control, and transparency. However, almost all of these features must be manually activated or enabled. For more details, see [Feature Overview](https://github.com/ungoogled-software/ungoogled-chromium/tree/master#feature-overview).

As this is a patch that enhances control, I'd argue this patch *does* apply.

**Comment by networkException** [comment]
> Besides, this patch does not apply.

that is a technical observation:

```
WARNING: Patch failed validation: extra/ungoogled-chromium/extension-search-path.patch
DEBUG: Specifically, file "chrome/common/chrome_paths.cc" failed validation: Line '#include "base/files/file_path.h"' does not match context line '#include "base/files/file_util.h"' from patch
DEBUG: PATCH_BIN env variable is not set
DEBUG: Output of "patch --dry-run" for this patch on this file:
checking file chrome/common/chrome_paths.cc
Hunk #1 FAILED at 4.
Hunk #2 FAILED at 511.
2 out of 2 hunks FAILED
```

**Comment by Pandapip1** [comment]
Sorry! Misinterpreted your statement.

**Comment by Pandapip1** [comment]
The patch should apply now.

**Comment by PF4Public** [comment]
> I'll try to take a closer look (can't promise when) at declarative extensions and whether ungoogled-chromium should put patches for it into its patchset

@networkException Have you had a chance to glance through? What's your opinion?

**Comment by networkException** [comment]
*with my nixpkgs chromium maintainer hat on* I don't see the patch as useful here or in packaging as there are ways not needing modifications which I would prefer anyways

**Comment by bendlas** [comment]
I would love to see this in UC. It's not just for including extensions from chromestore, but also for developing your own.

1. Carrying this patch in nixpkgs doesn't make sense, because it enables a substantial use case, which would then differ from other distros.
2. While there are workarounds, like managing the user's extention dir, this is substantially different and valuable in it's own right, because a system level extension also can't be messed up by a user messing up their browser profile.

**Comment by Pandapip1** [comment]
Just fixed a merge conflict. Would anyone from UC be willing to review this?

**Review by networkException — CHANGES_REQUESTED** [review]
No, this is not happening until it gets decided in upstream.

**Comment by bendlas** [comment]
> No, this is not happening until it gets decided in nixpkgs upstream.

In what way is nixpkgs to be considered upstream to this?

What decision should be taken by nixpkgs and how would it influence UC?

**Comment by Pandapip1** [comment]
I have also sent this patch to chromium upstream. It can be tracked here: https://chromium-review.googlesource.com/c/chromium/+/5650013

**Comment by networkException** [comment]
I think this has been discussed enough, solutions have been pointed out. This is definitely not a fit for us and very likely not for nixpkgs either.

Closeing as per https://github.com/ungoogled-software/ungoogled-chromium/issues/2932#issuecomment-2212516130

**Pull request closed without merging**
