### PR TITLE
Update to Chromium 120.0.6099.199

### LINKED ISSUE #2644: Hide side panel advertisement in the bookmarks folder
### Description

Remove annoying feature advertisement

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Chromium sometimes displays awful blue banners advertising tab groups, password manager, and other features, but at least they appear only on new profiles and can be dismissed. Someone not happy with this decided to shove the side panel trash instead of the bookmark bar more aggressively by placing this item on top of the "Other bookmarks" folder:
image

It just stays there permanently, as if the side panel icon is not enough.

If there's a flag for disabling the side panel icon (#hide-sidepanel-button), there also should be one for hiding other ways to open it. The #power-bookmarks-side-panel allowed it, but has expired.

### Possible solutions

Reintroduce expired "Power Bookmarks side panel" flag.

or

Introduce a flag for disabling all advertisements like this (I'm pretty sure they will not stop and will add only more similar garbage).

### Alternatives

Staying on an old version, removing all items from the "Other bookmarks" folder or refusing to use bookmarks.

### Additional context

A search for "Power Bookmarks Side Panel" or "Open Side Panel to see All Bookmarks" will show that many people are frustrated by these changes and want a way to remove this shortcut.

### LINKED ISSUE #2652: utils/domain_substitution.py revert calls extract_tar_file without supplying skip_unused
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

120.0.6099.129-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Missing parameter in revert function of domain_substitution.py

### How to Reproduce?

1. Clone my working [fork](https://github.com/SugaryHull/ungoogled-chromium-debian/) of ungoogled-chromium-debian into a Debian 12 install (the committed version is from before this issue)
2. `git submodule update --init --recursive`
3. `sudo mk-build-deps -i debian/control`
4. `dpkg-buildpackage -b -uc`

### Actual behaviour

Chromium itself compiles, but when `debian/rules` executes `domain_substitution.py revert` while preparing to package the linked binary, the revert function calls `extract_tar_file()` in `_extraction.py` without supplying the `skip_unused` argument, causing a TypeError that results in `dpkg-buildpackage` erroring out. 

### Expected behaviour

When the `skip_unused` argument and its associated checks are patched out of `_extraction.py`, `dpkg-buildpackage` works as expected and reverts the domain substitution changes to the Chromium source tree, allowing it to finish packaging.

### Relevant log output

```sh
Traceback (most recent call last):
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 370, in <module>
    main()
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 366, in main
    args.callback(args)
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 319, in _callback
    revert_substitution(args.cache, args.directory)
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 288, in revert_substitution
    extract_tar_file(domainsub_cache, extract_path, None)
TypeError: extract_tar_file() missing 1 required positional argument: 'skip_unused'
make[1]: *** [debian/rules:149: override_dh_prep] Error 1
```

### Additional context

This only seems to happen with the revert function of `domain_substitution.py`
See my [PR](https://github.com/ungoogled-software/ungoogled-chromium-debian/pull/335) for ungoogled-chromium-debian for more details

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 120.0.6099.199.  
I've also included a commit that adds a new UI removal for the side panel in All Bookmarks, fixes #2644 
and a commit that fixes the extract_tar_file call for the revert command, fixes #2652 

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/120.0.6099.129..120.0.6099.199?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/01/stable-channel-update-for-desktop.html)

### CODE REVIEW

**Comment by berkley4** [comment]
I'm still getting an error under debian when reverting domain substitution...

```
  File "/UC/build/src/debian/submodules/ungoogled-chromium/utils/_extraction.py", line 240, in extract_tar_file
    tar_bin = _find_extractor_by_cmd(extractors.get(ExtractorEnum.TAR))
                                     ^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'get'
```

A workaround is to hardcode tar_bin (ie tar_bin = "tar") in utils/_extraction.py.

**Comment by Ahrotahn** [comment]
Are you still using your changes removing `skip_unused`?  If so then `False` is being passed to `extractors` instead which is why it would complain about it being a boolean.

**Comment by berkley4** [comment]
Thinking that you had maybe fixed the skip_unused issue, I stopped removing it. I'm about to do another build, so I'll try again and report back.

**Comment by berkley4** [comment]
With a completely fresh build the issue seems to have gone. Sorry for the noise.

**Review by networkException — APPROVED** [review]

**Comment by teeminus** [comment]
Builds and runs fine for windows.

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
