### PR TITLE
Update to Chromium 108.0.5359.71/72

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 108.0.5359.71/72.

Notable changes:

* Updates to the safebrowsing patch due to [[3930883]](https://chromium-review.googlesource.com/c/chromium/src/+/3930883), [[3904931]](https://chromium-review.googlesource.com/c/chromium/src/+/3904931), and [[3910579]](https://chromium-review.googlesource.com/c/chromium/src/+/3910579)
* New addition to the safebrowsing patch due to [[3860312]](https://chromium-review.googlesource.com/c/chromium/src/+/3860312) and [[3919410]](https://chromium-review.googlesource.com/c/chromium/src/+/3919410)
* C++20 support has been enabled for linux and mac [(1284275)](https://bugs.chromium.org/p/chromium/issues/detail?id=1284275)
  * base::Feature needed to be changed due to this, so there are lots of changes across the patchset to the new declaration [(1364289)](https://bugs.chromium.org/p/chromium/issues/detail?id=1364289)
  * If you are building with a version of clang prior to version 15 (or if [this commit](https://github.com/llvm/llvm-project/commit/da6a14b91ad999327b41a9040577273591e4ad1d) hasn't been backported) then you will encounter linker errors for instances of std::u16string. You'll have to update or revert the new build changes:
<details><summary>diff</summary>

```diff
--- a/build/config/compiler/BUILD.gn
+++ b/build/config/compiler/BUILD.gn
@@ -589,15 +589,6 @@
       if (is_clang) {
         cflags_cc += [ "-fno-trigraphs" ]
       }
-    } else if (is_linux) {
-      # TODO(crbug.com/1284275): Switch to C++20 on all platforms.
-      if (is_clang) {
-        cflags_cc += [ "-std=${standard_prefix}++20" ]
-      } else {
-        # The gcc bots are currently using GCC 9, which is not new enough to
-        # support "c++20"/"gnu++20".
-        cflags_cc += [ "-std=${standard_prefix}++2a" ]
-      }
     } else {
       cflags_cc += [ "-std=${standard_prefix}++17" ]
     }
@@ -611,12 +602,7 @@
     # turned off we need the !is_nacl clause and the (is_nacl && is_clang)
     # clause, above.
     cflags_c += [ "-std=c11" ]
-    if (is_mac) {
-      # TODO(crbug.com/1284275): Switch to C++20 on all platforms.
-      cflags_cc += [ "-std=c++20" ]
-    } else {
       cflags_cc += [ "-std=c++17" ]
-    }
   }
 
   if (is_clang && current_os != "zos") {
```
</details>

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/107.0.5304.122..108.0.5359.72?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2022/11/stable-channel-update-for-desktop_29.html)

### CODE REVIEW

**Comment by a51kot** [comment]
[  298s] ERROR: 29 files could not be pruned.

 # Ungoogled Chromium changes
  _ungoogled_repo="$srcdir/$pkgname-$_uc_ver"
  _utils="${_ungoogled_repo}/utils"
  msg2 'Pruning binaries'
  python "$_utils/prune_binaries.py" ./ "$_ungoogled_repo/pruning.list"
  msg2 'Applying patches'
  python "$_utils/patches.py" apply ./ "$_ungoogled_repo/patches"
  msg2 'Applying domain substitution'
  python "$_utils/domain_substitution.py" apply -r "$_ungoogled_repo/domain_regex.list" \
    -f "$_ungoogled_repo/domain_substitution.list" -c domainsubcache.tar.gz ./

**Comment by a51kot** [comment]
@Ahrotahn why i got this  uncanny error

**Comment by PF4Public** [comment]
Builds and runs 👍🏻

**Comment by a51kot** [comment]
@PF4Public why  the update gives me errors (archlinux + obs)

[  220s] ERROR: 29 files could not be pruned.

https://build.opensuse.org/package/live_build_log/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium22/Arch/x86_64

**Comment by PF4Public** [comment]
@a51kot What steps have you performed to first isolate the issue yourself? You cannot just ask someone else to fix your issues for you.

**Comment by Ahrotahn** [comment]
@a51kot You're attempting to build 108.0.5359.48 with the 107.0.5304.110 patchset. You'll need to build with the changes in this PR.

**Comment by a51kot** [comment]
@Ahrotahn it worked kek  

whooops

**Comment by a51kot** [comment]
i got a new KEY error

[ 1265s] FAILED: libvk_swiftshader.so libvk_swiftshader.so.TOC 
[ 1265s] python3 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm"  --sofile="./libvk_swiftshader.so" --tocfile="./libvk_swiftshader.so.TOC" --output="./libvk_swiftshader.so" -- clang++ -shared -Wl,-soname="libvk_swiftshader.so" -Wl,-Bsymbolic -Wl,--version-script=../../third_party/swiftshader/src/Vulkan/vk_swiftshader.lds -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -no-canonical-prefixes -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--lto-O0 -fsanitize=cfi-vcall -fsanitize=cfi-icall -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o "./libvk_swiftshader.so" @"./libvk_swiftshader.so.rsp" 
[ 1265s] ld.lld: error: unable to find library -l:libffi_pic.a
[ 1265s] clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by a51kot** [comment]
@PF4Public @Ahrotahn i got a new KEY error

[ 1265s] FAILED: libvk_swiftshader.so libvk_swiftshader.so.TOC 
[ 1265s] python3 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm"  --sofile="./libvk_swiftshader.so" --tocfile="./libvk_swiftshader.so.TOC" --output="./libvk_swiftshader.so" -- clang++ -shared -Wl,-soname="libvk_swiftshader.so" -Wl,-Bsymbolic -Wl,--version-script=../../third_party/swiftshader/src/Vulkan/vk_swiftshader.lds -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -no-canonical-prefixes -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--lto-O0 -fsanitize=cfi-vcall -fsanitize=cfi-icall -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o "./libvk_swiftshader.so" @"./libvk_swiftshader.so.rsp" 
[ 1265s] ld.lld: error: unable to find library -l:libffi_pic.a
[ 1265s] clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by a51kot** [comment]
[_log.txt](https://github.com/ungoogled-software/ungoogled-chromium/files/10079740/_log.txt)
@PF4Public @Ahrotahn @networkException why i got this funny error

 [11920/51974] SOLINK ./libvk_swiftshader.so
[  873s] FAILED: libvk_swiftshader.so libvk_swiftshader.so.TOC 
[  873s] python3 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm"  --sofile="./libvk_swiftshader.so" --tocfile="./libvk_swiftshader.so.TOC" --output="./libvk_swiftshader.so" -- clang++ -shared -Wl,-soname="libvk_swiftshader.so" -Wl,-Bsymbolic -Wl,--version-script=../../third_party/swiftshader/src/Vulkan/vk_swiftshader.lds -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -no-canonical-prefixes -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--lto-O0 -fsanitize=cfi-vcall -fsanitize=cfi-icall -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o "./libvk_swiftshader.so" @"./libvk_swiftshader.so.rsp" 
[  873s] ld.lld: error: unable to find library -l:libffi_pic.a


System OBS arch template
Clang 14

**Comment by a51kot** [comment]
IT WORKS with use_system_libffi=true

**Comment by nerd** [comment]
getting this version to run on Gentoo (via pf4public's ebuild) required me to add [this patch](https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/plain/build/chromium-patches/disable-crashpad.patch?h=dev&id=5ae3a8912ea6f30b80b06cdd38e3f1d8aacb8bb5) to disable Crashpad, otherwise Chromium would fail to start. I am choosing to report this here as this seems to have also [affected the vanilla Chromium Snap build](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1993581), leading me to believe it is not a specific to Gentoo

**Comment by a51kot** [comment]
> getting this version to run on Gentoo (via pf4public's ebuild) required me to add [this patch](https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/plain/build/chromium-patches/disable-crashpad.patch?h=dev&id=5ae3a8912ea6f30b80b06cdd38e3f1d8aacb8bb5) to disable Crashpad, otherwise Chromium would fail to start. I am choosing to report this here as this seems to have also [affected the vanilla Chromium Snap build](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1993581), leading me to believe it is not a specific to Gentoo

and did u get surprises with libffi (me on arch

**Comment by PF4Public** [comment]
@nerd have you disabled `is_official_build`? I didn't have to use that patch to run chromium.

**Comment by nerd** [comment]
> have you disabled `is_official_build`? I didn't have to use that patch to run chromium.

I didn't do anything other than compiling the ebuild as given, with and without the patch.

**Comment by Ahrotahn** [comment]
I'm able to reproduce the issue.  The [existing patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/107.0.5304.110-1/patches/core/ungoogled-chromium/disable-crash-reporter.patch) to disable crash reporting has been nullified by [[3764621]](https://chromium-review.googlesource.com/c/chromium/src/+/3764621), so I'll spend some time later updating that for the new changes.

**Comment by a51kot** [comment]
@Ahrotahn 
i've got this   (on google code)
```
--- chrome/browser/ui/webui/crashes_ui.cc       2022-11-16 18:42:34.426369200 -0300
+++ chrome/browser/ui/webui/crashes_ui.cc.new   2022-11-24 18:25:28.151473516 -0300
@@ -198,7 +198,7 @@
   bool manual_uploads_supported = false;
 #if BUILDFLAG(IS_WIN) || BUILDFLAG(IS_MAC) || BUILDFLAG(IS_LINUX) || \
     BUILDFLAG(IS_ANDROID)
-  manual_uploads_supported = true;
+  manual_uploads_supported = false;
 #endif
   bool allow_manual_uploads =
       manual_uploads_supported &&

```

**Comment by a51kot** [comment]
@Ahrotahn @PF4Public @networkException could someone tell me if my patch  helps there   or  iof its useless

**Comment by Ahrotahn** [comment]
@a51kot Since we build without reporting `IsMetricsAndCrashReportingEnabled()` will return false, so that change will have no effect.

**Comment by Ahrotahn** [comment]
With the new patch I've been able to make packages without including chrome_crashpad_handler on linux.  It should be fine on other platforms, but it would be good to have extra confirmation on that.

**Comment by a51kot** [comment]
@Ahrotahn 
Google released a 108 update (it will jump to stable)  
https://chromereleases.googleblog.com/2022/11/beta-channel-update-for-desktop_28.html

**Comment by a51kot** [comment]
@Ahrotahn @PF4Public @networkException chrome released a new beta update 108.0.5359.62

**Comment by networkException** [comment]
I've had enough of this

**Comment by Ahrotahn** [comment]
108.0.5359.72 has been released for windows, but the dispatch won't trigger for a couple more hours unless they run it manually.  I'll add that update after the tarball is available.

**Comment by PF4Public** [comment]
@Ahrotahn please resolve the conflict in `chromium_version.txt`, I guess it is due to us committing another version in between.

**Comment by Ahrotahn** [comment]
I had forgotten about .121/122!  I've also taken the opportunity to squash the commits down.

**Review by PF4Public — APPROVED** [review]
I'm afraid I won't be able to build in the coming days, but since I have a functioning .48, I'd approve now and build later :)

**Review by networkException — APPROVED** [review]

**Comment by Ahrotahn** [comment]
Its always been pretty annoying how github doesn't have a fast-forward option for merging PRs through the webui. That would be a way to be able to keep the signature verification for the commits without having github resign them.

You can do the merge locally but I thought that branch protection would prevent pushing it back. Apparently it is still possible to do this with branch protection enabled if a PR for the same merge exists and all of the status checks for that PR have passed. The PR will be closed as merged automatically after the change goes through.

It would still be nice to have that as a button in the web interface though...

**Comment by jstkdng** [comment]
so uh.... what happened to the release for this version?

**Comment by networkException** [comment]
haven't had time yet

**Comment by Ahrotahn** [comment]
Sorry about that, I didn't mean to add extra pressure in your life!

**Comment by PF4Public** [comment]
Is signature verification a major problem? I take it that it gives a proof that commits originate from the same author. Is it of high significance (for this project)? Should we enforce this?

**Comment by Ahrotahn** [comment]
I don't think its a problem, at least on github since they don't really make it easy. Its just annoying that they go through so much effort to have people set up MFA, add keys, and sign commits only to trash them through PRs with more than one commit.

**Comment by networkException** [comment]
> Sorry about that, I didn't mean to add extra pressure in your life!

oh it's fine don't worry

**Comment by networkException** [comment]
Commit verification is nice in theory and I really want to look into that (as well as signing artifacts and so on) more heavily for this project in the future.

For now my signature of the tag also puts a stamp of approval on all commits it references but of course that isn't as nice as having all commits verified properly as well

**Pull request merged**
