### PR TITLE
Update to Chromium 121.0.6167.85

### LINKED ISSUE #2673: Remove anoying set chromium as default browser banner
### Description

Removing the set chromium as default browser banner

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I'm always annoyed starting ungoogled chromium and then seeing a banner asking me, if I want to set it as default browser. Unfortunately there isn't an easy setting for disabling this banner, besides -no-default-browser-check as an argument at launchtime or a specific enterprise configuration.
image
(Screenshot in german)

### Possible solutions

Remove this annoying set chromium as default browser banner or an option to disable it in chrome://flags/ or settings.

### Alternatives

_No response_

### Additional context

_No response_

### LINKED ISSUE #2682: Remove Third party cookie consent feedback from the menu
### Description

Remove "Send Feedback. Help us improve Chrome by telling us why you allowed third-party cookies"

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

When you need to allow third-party cookies for a certain site, Chromium adds a survey to the bottom of the menu, which is already too huge and ugly. Thankfully, it doesn't send anything.

Example site: https://alanhogan.github.io/web-experiments/3rd/third-party-cookies.html

image

As most of the garbage nobody asked for, it is of course also accompanied by a blue notification:
image

### Possible solutions

Include the survey in https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/remove-uneeded-ui.patch

### Alternatives

_No response_

### Additional context

Perhaps this should also be considered as an upstream issue since the survey is shown even if FeedbackSurveysEnabled, MetricsReportingEnabled, or UserFeedbackAllowed policies are set to Disabled.
But it is not functional in ungoogled version, so is worth removing anyway.

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 121.0.6167.85.  

Notes:

* The option to clear cookies on exit has been removed in [[5053746]](https://chromium-review.googlesource.com/c/chromium/src/+/5053746), so `prefs-only-keep-cookies-until-exit.patch` has been removed as well as the entry on the first run page

* WEI has been removed in [[5001989]](https://chromium-review.googlesource.com/c/chromium/src/+/5001989), so `disable-web-environment-integrity.patch` has been removed

* There was a new addition to the safebrowsing patch for [[4973340]](https://chromium-review.googlesource.com/c/chromium/src/+/4973340)

* `google-java-format` has been added to the contingent paths

* `no-default-browser-check` has been added to `add-flags-for-existing-switches.patch`, fixes #2673

* A new removal for the feedback entry in the third-party cookie popup, fixes #2682

<br>

* If building with a prior version of clang [[5030335]](https://chromium-review.googlesource.com/c/chromium/src/+/5030335) will need to be reverted and the constexpr introduced in [[5059164]](https://chromium-review.googlesource.com/c/chromium/src/+/5059164) will need to be removed:
    <details><summary>diff</summary>

    ```diff
    --- a/components/performance_manager/resource_attribution/query_params.h
    +++ b/components/performance_manager/resource_attribution/query_params.h
    @@ -27,7 +27,7 @@
       QueryParams(const QueryParams& other);
       QueryParams& operator=(const QueryParams& other);
     
    -  friend constexpr bool operator==(const QueryParams&,
    +  friend bool operator==(const QueryParams&,
                                        const QueryParams&) = default;
     
       // Individual resource contexts to measure.
    ```
    </details>

* The Rust QR code generator is being shipped with [[5064208]](https://chromium-review.googlesource.com/c/chromium/src/+/5064208) and can be reverted with:
    <details><summary>diff</summary>

    ```diff
    --- a/components/qr_code_generator/BUILD.gn
    +++ b/components/qr_code_generator/BUILD.gn
    @@ -39,21 +39,11 @@
       ]
       deps = [
         ":qr_code_generator_features",
    -    ":qr_code_generator_ffi_glue",
         "//base",
       ]
       public_deps = [ "//base" ]
     }
     
    -rust_static_library("qr_code_generator_ffi_glue") {
    -  allow_unsafe = true  # Needed for FFI that underpins the `cxx` crate.
    -  crate_root = "qr_code_generator_ffi_glue.rs"
    -  sources = [ "qr_code_generator_ffi_glue.rs" ]
    -  cxx_bindings = [ "qr_code_generator_ffi_glue.rs" ]
    -  visibility = [ ":qr_code_generator" ]
    -  deps = [ "//third_party/rust/qr_code/v2:lib" ]
    -}
    -
     source_set("unit_tests") {
       testonly = true
       sources = [ "qr_code_generator_unittest.cc" ]
    --- a/components/qr_code_generator/qr_code_generator.cc
    +++ b/components/qr_code_generator/qr_code_generator.cc
    @@ -11,12 +11,10 @@
     #include <vector>
     
     #include "base/check_op.h"
    -#include "base/containers/span_rust.h"
     #include "base/memory/raw_ptr.h"
     #include "base/notreached.h"
     #include "base/numerics/safe_conversions.h"
     #include "components/qr_code_generator/features.h"
    -#include "components/qr_code_generator/qr_code_generator_ffi_glue.rs.h"
     
     namespace qr_code_generator {
     
    @@ -572,31 +570,6 @@
       return sum;
     }
     
    -absl::optional<QRCodeGenerator::GeneratedCode> GenerateQrCodeUsingRust(
    -    base::span<const uint8_t> in,
    -    absl::optional<int> min_version) {
    -  rust::Slice<const uint8_t> rs_in = base::SpanToRustSlice(in);
    -
    -  // `min_version` might come from a fuzzer and therefore we use a lenient
    -  // `saturated_cast` instead of a `checked_cast`.
    -  int16_t rs_min_version =
    -      base::saturated_cast<int16_t>(min_version.value_or(0));
    -
    -  std::vector<uint8_t> result_pixels;
    -  size_t result_width = 0;
    -  bool result_is_success = generate_qr_code_using_rust(
    -      rs_in, rs_min_version, result_pixels, result_width);
    -
    -  if (!result_is_success) {
    -    return absl::nullopt;
    -  }
    -  QRCodeGenerator::GeneratedCode code;
    -  code.data = std::move(result_pixels);
    -  code.qr_size = base::checked_cast<int>(result_width);
    -  CHECK_EQ(code.data.size(), static_cast<size_t>(code.qr_size * code.qr_size));
    -  return code;
    -}
    -
     }  // namespace
     
     QRCodeGenerator::QRCodeGenerator() = default;
    @@ -617,10 +590,6 @@
         return absl::nullopt;
       }
     
    -  if (IsRustyQrCodeGeneratorFeatureEnabled()) {
    -    return GenerateQrCodeUsingRust(in, min_version);
    -  }
    -
       std::vector<Segment> segments;
       const QRVersionInfo* version_info = nullptr;
     
    ```
    </details>
    They plan to remove the c++ code in a month, so I'll work on removing the llvm and rust contingent paths for platforms that need to build with the included sources.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/120.0.6099.224..121.0.6167.85?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/01/stable-channel-update-for-desktop_23.html)

### CODE REVIEW

**Comment by teeminus** [comment]
Builds and runs fine on windows with the Rust QR code generator patch. I also had to update the safebrowsing patch because linking would fail otherwise:

```
--- a/chrome/browser/chrome_content_browser_client.cc
+++ b/chrome/browser/chrome_content_browser_client.cc
@@ -7107,6 +7044,7 @@ ChromeContentBrowserClient::GetAsyncCheckTracker(
     bool is_consumer_lookup_enabled,
     safe_browsing::hash_realtime_utils::HashRealTimeSelection
         hash_realtime_selection) {
+  return nullptr;
   content::WebContents* contents = wc_getter.Run();
   if (!contents || !safe_browsing_service_ ||
       !safe_browsing_service_->ui_manager()) {
```

I pasted the patch here in case it is required some any of the other platforms. If not, I will add it to the windows safebrowsing removal patch. I am also not quite sure if the `return nullptr;` needs to be placed after the `content::WebContents* contents = wc_getter.Run();`...

**Comment by Ahrotahn** [comment]
Thanks @teeminus, I've updated the PR and added one more ui removal as well.

**Comment by LeFroid** [comment]
I ran into the following error in HistoryService building with clang 17. Looked at the delta between chromium 120 and 121 in this class and didn't see anything obvious. Maybe some default compiler flag has been changed?

```In file included from ../../components/history/core/browser/history_service.cc:18:
In file included from ../../components/history/core/browser/history_service.h:10:
In file included from /usr/include/c++/v1/memory:884:
In file included from /usr/include/c++/v1/__memory/allocate_at_least.h:13:
In file included from /usr/include/c++/v1/__memory/allocator_traits.h:15:
[1m/usr/include/c++/v1/__memory/pointer_traits.h:118:22: [0m[0;1;31merror: [0m[1mimplicit instantiation of undefined template 'std::__pointer_traits_element_type<base::SafeRef<history::HistoryService>>'[0m
  118 |     typedef typename __pointer_traits_element_type<pointer>::type    element_type;[0m
      | [0;1;32m                     ^
[0m[1m/usr/include/c++/v1/__memory/pointer_traits.h:182:20: [0m[0;1;30mnote: [0min instantiation of template class 'std::pointer_traits<base::SafeRef<history::HistoryService>>' requested here[0m
  182 |     decltype((void)pointer_traits<_Pointer>::to_address(std::declval<const _Pointer&>()))[0m
      | [0;1;32m                   ^
[0m[1m/usr/include/c++/v1/__memory/pointer_traits.h:195:59: [0m[0;1;30mnote: [0mduring template argument deduction for class template partial specialization '_HasToAddress<_Pointer, decltype((void)pointer_traits<_Pointer>::to_address(std::declval<const _Pointer &>()))>' [with _Pointer = base::SafeRef<history::HistoryService>][0m
  195 |   static const bool value = _HasArrow<_Pointer>::value || _HasToAddress<_Pointer>::value;[0m
      | [0;1;32m                                                          ^
[0m[1m/usr/include/c++/v1/__memory/pointer_traits.h:195:59: [0m[0;1;30mnote: [0min instantiation of template class 'std::_HasToAddress<base::SafeRef<history::HistoryService>>' requested here[0m
[1m/usr/include/c++/v1/__type_traits/conjunction.h:27:32: [0m[0;1;30mnote: [0min instantiation of template class 'std::_IsFancyPointer<base::SafeRef<history::HistoryService>>' requested here[0m
   27 | __expand_to_true<__enable_if_t<_Pred::value>...> __and_helper(int);[0m
      | [0;1;32m                               ^
[0m[1m/usr/include/c++/v1/__type_traits/conjunction.h:38:39: [0m[0;1;30mnote: [0mwhile substituting explicitly-specified template arguments into function template '__and_helper' [0m
   38 | using _And _LIBCPP_NODEBUG = decltype(std::__and_helper<_Pred...>(0));[0m
      | [0;1;32m                                      ^
[0m[1m/usr/include/c++/v1/__memory/pointer_traits.h:200:5: [0m[0;1;30mnote: [0m(skipping 8 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)[0m
  200 |     _And<is_class<_Pointer>, _IsFancyPointer<_Pointer> >::value[0m
      | [0;1;32m    ^
[0m[1m../../base/functional/bind_internal.h:1395:34: [0m[0;1;30mnote: [0min instantiation of template class 'base::internal::UnderlyingReceiverType<const base::SafeRef<history::HistoryService> &>' requested here[0m
 1395 |   using Type = TypeList<typename UnderlyingReceiver::Type,[0m
      | [0;1;32m                                 ^
[0m[1m../../base/functional/bind_internal.h:1763:51: [0m[0;1;30mnote: [0min instantiation of template class 'base::internal::MakeUnwrappedTypeList<false, true, base::SafeRef<history::HistoryService> &&>' requested here[0m
 1763 |                           BoundArgsList, typename UnwrappedArgsList::Type,[0m
      | [0;1;32m                                                  ^
[0m[1m../../base/functional/bind_internal.h:1866:45: [0m[0;1;30mnote: [0min instantiation of function template specialization 'base::internal::BindHelper<base::RepeatingCallback>::Bind<void (history::HistoryService::*)(), base::SafeRef<history::HistoryService>>' requested here[0m
 1866 |       return BindHelper<RepeatingCallback>::Bind(std::forward<Functor>(functor),[0m
      | [0;1;32m                                            ^
[0m[1m../../base/functional/bind.h:66:59: [0m[0;1;30mnote: [0min instantiation of member function 'base::internal::BindRepeatingHelper<void (history::HistoryService::*)(), base::SafeRef<history::HistoryService>>::BindRepeating' requested here[0m
   66 |   return internal::BindRepeatingHelper<Functor, Args...>::BindRepeating([0m
      | [0;1;32m                                                          ^
[0m[1m../../components/history/core/browser/history_service.cc:447:17: [0m[0;1;30mnote: [0min instantiation of function template specialization 'base::BindRepeating<void (history::HistoryService::*)(), base::SafeRef<history::HistoryService>>' requested here[0m
  447 |           base::BindRepeating([0m
      | [0;1;32m                ^
[0m[1m/usr/include/c++/v1/__memory/pointer_traits.h:38:8: [0m[0;1;30mnote: [0mtemplate is declared here[0m
   38 | struct __pointer_traits_element_type;[0m
      | [0;1;32m       ^
[0m1 error generated.```

**Comment by Ahrotahn** [comment]
That seems to be the same issue as https://github.com/llvm/llvm-project/issues/67449
You could temporarily apply the fix to [libcxx/include/__memory/pointer_traits.h](https://github.com/llvm/llvm-project/commit/078651b6de4b767b91e3e6a51e5df11a06d7bc4f#diff-cdad0245814da2f53716b70103381880154ed6ea30dcc34cfcc6c51a164c4b0d) if there isn't a newer version available that already includes the change.

**Comment by LeFroid** [comment]
I had to apply a minor patch to Blink to get the build working with my system's libxml2 (v2.11.5), otherwise this built and ran perfectly! Thanks again for finding out the issue with libc++, that patch to [pointer_traits.h](https://github.com/llvm/llvm-project/commit/078651b6de4b767b91e3e6a51e5df11a06d7bc4f#diff-cdad0245814da2f53716b70103381880154ed6ea30dcc34cfcc6c51a164c4b0d) resolved the clang issue.

This is the blink patch for libxml,
```
--- a/third_party/blink/renderer/core/xml/xslt_processor.h
+++ b/third_party/blink/renderer/core/xml/xslt_processor.h
@@ -77,7 +77,7 @@
 
   void reset();
 
-  static void ParseErrorFunc(void* user_data, const xmlError*);
+  static void ParseErrorFunc(void* user_data, xmlError*);
   static void GenericErrorFunc(void* user_data, const char* msg, ...);
 
   // Only for libXSLT callbacks
--- a/third_party/blink/renderer/core/xml/xslt_processor_libxslt.cc
+++ b/third_party/blink/renderer/core/xml/xslt_processor_libxslt.cc
@@ -66,7 +66,7 @@
   // It would be nice to do something with this error message.
 }
 
-void XSLTProcessor::ParseErrorFunc(void* user_data, const xmlError* error) {
+void XSLTProcessor::ParseErrorFunc(void* user_data, xmlError* error) {
   FrameConsole* console = static_cast<FrameConsole*>(user_data);
   if (!console)
     return;

```

**Review by networkException — APPROVED** [review]
(tested building without rust)

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
