### PR TITLE
Make --cache argument to domain_substitution.py optional

### PR DESCRIPTION
**Pull request by iskunk**
In my workflow, the cache file created by the domain substitution script is not needed, and just slows things down. (I am running the script on a copy of the tree, so saving the original files is redundant.)

This was written in a way that minimizes code changes. Please let me know if a different approach is desired.

### CODE REVIEW

**Review by Ahrotahn — APPROVED** [review]
This looks good to me!

I don't know if it's something on my end, but for some reason #2135 doesn't show up in the filter to link the issue to the PR.  Weird!

**Comment by PF4Public** [comment]
> #2135 doesn't show up in the filter to link the issue to the PR. Weird!

Same for me. Maybe GitHub limits the number of issues in "Development" menu by time or something like that.

That's why I decided to link it in a message instead, so as not to forget to close it after merge.

**Comment by PF4Public** [comment]
@networkException Do you have any opinion on this PR?

**Review by networkException — DISMISSED** [review]
Looks very reasonable

**Comment by PF4Public** [comment]
I'll test this PR locally and merge if all goes well.

**Comment by iskunk** [comment]
Hi @PF4Public, I've updated the commit with that and a few additional lines conditionalized under `if domainsub_cache`. Please let me know if anything more is needed.

**Review by PF4Public — APPROVED** [review]
Without a cache domain substitution feels faster, awesome!

**Review by networkException — APPROVED** [review]

**Comment by PF4Public** [comment]
Thanks @iskunk

**Pull request merged**
