### PR TITLE
Update to Chromium 124.0.6367.78

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 124.0.6367.78.  
There were no notable changes on our end.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/124.0.6367.60..124.0.6367.78?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_24.html)

### CODE REVIEW

**Comment by clickot** [comment]
portable linux builds fine and runs at least on manjaro and ubuntu 20.04 upwards including 24.04

**Review by networkException — APPROVED** [review]

**Comment by Ahrotahn** [comment]
Since .91 just dropped I'll merge this in a bit, then the readme change

**Comment by networkException** [comment]
I can also do that and tag it, however you like

**Comment by Ahrotahn** [comment]
Sure, I'll let you handle that then!

**Pull request merged**
