### PR TITLE
Update to Chromium 122.0.6261.57

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 122.0.6261.57.

Notes:

* Lots of small `absl` to `std` namespace changes due to [[5200092]](https://chromium-review.googlesource.com/c/chromium/src/+/5200092)

* The Inox safebrowsing patch had some updates for [[5147288]](https://chromium-review.googlesource.com/c/chromium/src/+/5147288) and removals for [[5142470]](https://chromium-review.googlesource.com/c/chromium/src/+/5142470)

* The safebrowsing patch had new updates for [[5075464]](https://chromium-review.googlesource.com/c/chromium/src/+/5075464), [[5084990]](https://chromium-review.googlesource.com/c/chromium/src/+/5084990), [[5100289]](https://chromium-review.googlesource.com/c/chromium/src/+/5100289), [[5117338]](https://chromium-review.googlesource.com/c/chromium/src/+/5117338), [[5142470]](https://chromium-review.googlesource.com/c/chromium/src/+/5142470), and [[5171260]](https://chromium-review.googlesource.com/c/chromium/src/+/5171260)

* The block requests patch had a removal for [[5090073]](https://chromium-review.googlesource.com/c/chromium/src/+/5090073)

* The privacy sandbox patch had removals for [[5158747]](https://chromium-review.googlesource.com/c/chromium/src/+/5158747) and [[5164112]](https://chromium-review.googlesource.com/c/chromium/src/+/5164112)

* A new addition to the remove uneeded ui patch for [[5169812]](https://chromium-review.googlesource.com/c/chromium/src/+/5169812)

* A small change to the close confirmation patch for [[5140028]](https://chromium-review.googlesource.com/c/chromium/src/+/5140028)

<br>

For prior clang versions [[5132129]](https://chromium-review.googlesource.com/c/chromium/src/+/5132129) will need to be reverted in addition to [[5030335]](https://chromium-review.googlesource.com/c/chromium/src/+/5030335) like the last version.  There are also a few more constexpr changes needed as well:
<details><summary>diff</summary>

```diff
--- a/base/types/strong_alias.h
+++ b/base/types/strong_alias.h
@@ -110,7 +110,7 @@
   // a `StrongAlias<W>`.
   friend constexpr auto operator<=>(const StrongAlias& lhs,
                                     const StrongAlias& rhs) = default;
-  friend constexpr bool operator==(const StrongAlias& lhs,
+  friend bool operator==(const StrongAlias& lhs,
                                    const StrongAlias& rhs) = default;
 
   // Hasher to use in std::unordered_map, std::unordered_set, etc.
--- a/components/autofill/core/common/unique_ids.h
+++ b/components/autofill/core/common/unique_ids.h
@@ -137,7 +137,7 @@
 
   friend constexpr auto operator<=>(const GlobalId<RendererId>& lhs,
                                     const GlobalId<RendererId>& rhs) = default;
-  friend constexpr bool operator==(const GlobalId<RendererId>& lhs,
+  friend bool operator==(const GlobalId<RendererId>& lhs,
                                    const GlobalId<RendererId>& rhs) = default;
 };
 
--- a/components/performance_manager/resource_attribution/query_params.h
+++ b/components/performance_manager/resource_attribution/query_params.h
@@ -29,7 +29,7 @@
   ContextCollection(const ContextCollection& other);
   ContextCollection& operator=(const ContextCollection& other);
 
-  friend constexpr bool operator==(const ContextCollection&,
+  friend bool operator==(const ContextCollection&,
                                    const ContextCollection&) = default;
 
   // Adds `context` to the collection.
@@ -67,7 +67,7 @@
   QueryParams(const QueryParams& other);
   QueryParams& operator=(const QueryParams& other);
 
-  friend constexpr bool operator==(const QueryParams&,
+  friend bool operator==(const QueryParams&,
                                    const QueryParams&) = default;
 
   // Resource types to measure.
```
</details>

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/121.0.6167.184..122.0.6261.57?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/02/stable-channel-update-for-desktop_20.html)

### CODE REVIEW

**Comment by teeminus** [comment]
Builds and runs fine for windows.

Linking failed on first try:
```
lld-link: error: undefined symbol: public: static class safe_browsing::FileTypePolicies * __cdecl safe_browsing::FileTypePolicies::GetInstance(void)
>>> referenced by ../../chrome/browser/download/download_ui_safe_browsing_util.cc
>>>               obj/chrome/browser\browser/download_ui_safe_browsing_util.obj

lld-link: error: undefined symbol: public: __int64 __cdecl safe_browsing::FileTypePolicies::UmaValueForFile(class base::FilePath const &) const
>>> referenced by ../../chrome/browser/download/download_ui_safe_browsing_util.cc
>>>               obj/chrome/browser\browser/download_ui_safe_browsing_util.obj
```

I fixed it with the following patch:
```
--- a/chrome/browser/downloaddownload_ui_safe_browsing_util.cc
+++ b/chrome/browser/downloaddownload_ui_safe_browsing_util.cc
@@ -64,12 +64,6 @@ bool CanUserTurnOnSafeBrowsing(Profile* profile) {
 void RecordDownloadDangerPromptHistogram(
     const std::string& proceed_or_shown_suffix,
     const download::DownloadItem& item) {
-  int64_t file_type_uma_value =
-      safe_browsing::FileTypePolicies::GetInstance()->UmaValueForFile(
-          item.GetTargetFilePath());
-  base::UmaHistogramSparse(
-      GetDangerPromptHistogramName(proceed_or_shown_suffix, item),
-      file_type_uma_value);
 }
 
 #if BUILDFLAG(FULL_SAFE_BROWSING)
```

**Comment by Ahrotahn** [comment]
Thanks @teeminus, I'll update that along with the version bump later today.

**Review by networkException — APPROVED** [review]

**Comment by teeminus** [comment]
.57 builds and runs fine on windows 👍

**Comment by clickot** [comment]
portablelinux builds and runs at least on manjaro and ubuntu incl. 20.04

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
