### PR TITLE
Per-platform version check

### PR DESCRIPTION
**Pull request by PF4Public**
I was thinking of something like this in https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/158#issuecomment-1172274425

Issues should look like this: https://github.com/PF4Public/ungoogled-chromium/issues/22

Android was omitted as currently not very active.

TODO-list before merging:

- [x] Change the if condition 
- [x] Squash everything

### CODE REVIEW

**Comment by PF4Public** [comment]
Oh by the way, how should be the Mac OS written? Is it "macOS" nowadays?

**Comment by networkException** [comment]
yep "macOS" since 2016

**Comment by PF4Public** [comment]
Would it be OK to create either a single "all platforms issue" or three issues each for its own platform? We still can link all of them to a single PR and close simultaneously.
Look [here](https://github.com/PF4Public/ungoogled-chromium/issues) for all of them in one place.

**Comment by PF4Public** [comment]
> I think trying to further group Windows and macOS in this example would just be unnecessarily complicated, especially without a proper scripting language

My thought exactly :)

I'll prepare this draft for merging then. After we merge the version-bump PR of course.

**Review by networkException — APPROVED** [review]

**Review by Ahrotahn — APPROVED** [review]

**Comment by teeminus** [comment]
How do we handle version differences between eg. windows and linux? The core repo uses the linux version and the patches are updated for that. What if we need to modify core patches for a more recent windows release?

**Comment by PF4Public** [comment]
I thought there was a suggestion to have tags for all versions in this repo and then use respective ones in downstream repos with there-needed patches.

**Comment by networkException** [comment]
Yes we should probably do that even without any changes to patches or lists, avoids confusion and keeps things consistent

**Pull request merged**
