### PR TITLE
Update to Chromium 130.0.6723.116

### PR DESCRIPTION
**Pull request by networkException**
This PR updates to Chromium 130.0.6723.116
There were no notable changes needed on our end.  

Something something tarball builders I'm sad I can't build it with Nix yet :(

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/130.0.6723.91..130.0.6723.116?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/11/stable-channel-update-for-desktop.html)

### CODE REVIEW

**Review by Ahrotahn — APPROVED** [review]
Builds and runs fine on my end, thanks @networkException!

**Comment by clickot** [comment]
clones, builds and runs fine for portable linux

**Comment by Cubik65536** [comment]
Clones, builds, and runs fine for macOS (arm64).

**Comment by teeminus** [comment]
Clones, builds, and runs fine for windows

**Pull request merged**
