### PR TITLE
Update to Chromium 124.0.6367.60

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 124.0.6367.60.

Notes:

* The block-trk-and-subdomains patch had a change for [[5372940]](https://chromium-review.googlesource.com/c/chromium/src/+/5372940)

* The privacy sandbox patch had a removal for [[5355850]](https://chromium-review.googlesource.com/c/chromium/src/+/5355850)

* Some changes in fix-building-with-prunned-binaries.patch have been removed since those sections are now gated correctly in [[5314821]](https://chromium-review.googlesource.com/c/chromium/src/+/5314821).  There's also an updated section for [[5302637]](https://chromium-review.googlesource.com/c/chromium/src/+/5302637) and [[5314624]](https://chromium-review.googlesource.com/c/chromium/src/+/5314624)

* The safebrowsing patch had new additions for [[5348385]](https://chromium-review.googlesource.com/c/chromium/src/+/5348385), [[5356219]](https://chromium-review.googlesource.com/c/chromium/src/+/5356219), [[5350320]](https://chromium-review.googlesource.com/c/chromium/src/+/5350320), [[5314847]](https://chromium-review.googlesource.com/c/chromium/src/+/5314847), and [[5362204]](https://chromium-review.googlesource.com/c/chromium/src/+/5362204)

* remove-unused-preferences-fields.patch had additions for the changes in [[5307157]](https://chromium-review.googlesource.com/c/chromium/src/+/5307157), [[5385966]](https://chromium-review.googlesource.com/c/chromium/src/+/5385966), [[5353046]](https://chromium-review.googlesource.com/c/chromium/src/+/5353046), [[5317734]](https://chromium-review.googlesource.com/c/chromium/src/+/5317734), and [[5385966]](https://chromium-review.googlesource.com/c/chromium/src/+/5385966)

* The clone script has been updated to handle a scenario where an existing checkout that includes a submodule is updated to a different version that doesn't include the submodule and would leave the submodule in place

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/123.0.6312.122..124.0.6367.60?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_16.html)

### CODE REVIEW

**Comment by Ahrotahn** [comment]
Also I encountered an issue with generated ninja files looking for json.gz files in a relative path higher than the current build directory.  I figure it might be something odd with my build environment since it seems to have no problem on Google's end.  This needs some further investigation and I would be interested to know if it affects anyone else.  It looks like this was introduced in [[5332214]](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5332214) due to the changes in [[5330907]](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5330907).  I'm currently working around this with the following change:
```diff
--- a/third_party/devtools-frontend/src/front_end/BUILD.gn
+++ b/third_party/devtools-frontend/src/front_end/BUILD.gn
@@ -185,7 +185,6 @@
     "panels/sources/components:unittests",
     "panels/timeline:unittests",
     "panels/timeline/components:unittests",
-    "panels/timeline/fixtures/traces",
     "panels/timeline/track_appenders:unittests",
     "panels/utils:unittests",
     "panels/web_audio:unittests",
```

**Comment by teeminus** [comment]
> Also I encountered an issue with generated ninja files looking for json.gz files in a relative path higher than the current build directory.  I figure it might be something odd with my build environment since it seems to have no problem on Google's end.  This needs some further investigation and I would be interested to know if it affects anyone else.


I had to apply the patch for windows as well.

**Comment by clickot** [comment]
I also had to apply the patch for portable linux

**Comment by Ahrotahn** [comment]
So I've just had a chance to dig into this further and found that those files _were_ being pruned.  I was looking at a clean source directory and the odd paths were a red herring.  🤦
That change is correct, I'll add it to fix-building-with-prunned-binaries.patch along with the next bump.

**Comment by teeminus** [comment]
> I'm getting a linking error on NixOS, might not be our fault:
> 
> 
> 
> ```
> 
> ld.lld: error: undefined symbol: safe_browsing::ChromeEnterpriseRealTimeUrlLookupServiceFactory::GetForProfile(Profile*)
> 
> >>> referenced by data_protection_navigation_observer.cc
> 
> ```

I got the same error on windows.

**Comment by networkException** [comment]
What did you do in the patch?

**Comment by Ahrotahn** [comment]
I updated the commit to deal with that linking issue and rebased over the readme change.  
Did you encounter that issue on your arch build?

**Comment by clickot** [comment]
also get the same linking error at the end of portable linux build:
ld.lld: error: undefined symbol: safe_browsing::ChromeEnterpriseRealTimeUrlLookupServiceFactory::GetForProfile(Profile*)
>>> referenced by data_protection_navigation_observer.cc

**Comment by teeminus** [comment]
Linking for windows succeeds now without me having to update the windows patch.

I noticed that the 124 windows installer is around 10MB bigger than the last 123 release. Did anyone else noticed something similar for their platform?

**Review by networkException — APPROVED** [review]

**Comment by networkException** [comment]
Looks like we might not get this properly approved in time, unless there are any concerns left I'd merge this anyways when I wake up

**Comment by clickot** [comment]
@networkException so when do you wake up? :-D

**Comment by networkException** [comment]
Already did, was busy with work :D

**Comment by clickot** [comment]
that's what everybody says... :-D

**Comment by PF4Public** [comment]
> that's what everybody says... :-D

Me too, me too! :D

**Pull request merged**
