### PR TITLE
Update to Chromium 120.0.6099.224/234

### PR DESCRIPTION
**Pull request by networkException**
This PR updates to chromium 120.0.6099.224 and 120.0.6099.234.
There were no changes needed on our end.

[Change log](https://chromium.googlesource.com/chromium/src/+log/120.0.6099.216..120.0.6099.234?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/01/stable-channel-update-for-desktop_16.html)

### CODE REVIEW

**Review by Ahrotahn — APPROVED** [review]

**Comment by networkException** [comment]
Builds and runs as well

**Comment by Ahrotahn** [comment]
Do you get that with a clean build?

**Comment by teeminus** [comment]
I always do a clean build, but I will try again. Just in case I messed up the previous cleanup...

**Comment by teeminus** [comment]
> Do you get that with a clean build?  

You were absolutely right, I removed the build folder and started over, now it seems to work fine. (Although there are still 10k files left to compile)

Sorry for wasting your time 🫤

**Review by PF4Public — APPROVED** [review]

**Comment by Ahrotahn** [comment]
No worries, that's something I've encountered before.  I don't have my build script automatically remove the output for situations where I want to work with incremental builds, and errors with the generated files are usually a sign I've forgotten to clear it out.

**Pull request merged**
