### PR TITLE
Update to Chromium 114.0.5735.90/91

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 114.0.5735.90/91.

Notes:
* There were a handful of changes to the safebrowsing patch mostly due to [[4383029]](https://chromium-review.googlesource.com/c/chromium/src/+/4383029)
* The last of the ntp snippets were removed in [[4395467]](https://chromium-review.googlesource.com/c/chromium/src/+/4395467)
* The ip6 check has been updated to be asyc in [[3941746]](https://chromium-review.googlesource.com/c/chromium/src/+/3941746)
* The guest scheme has been removed in [[4379157]](https://chromium-review.googlesource.com/c/chromium/src/+/4379157)

<b></b>

* Some upstream patches will be required until they make it into a release:
  * A couple typenames were left out and fixed in [[4526465]](https://chromium-review.googlesource.com/c/chromium/src/+/4526465)
  * <del>The fix in [[4534915]](https://chromium-review.googlesource.com/c/chromium/src/+/4534915) since we build without the tflite lib.</del> This is included now

* If your version of clang doesn't include https://github.com/llvm/llvm-project/commit/a4d3bc68142e67c1cbceef3ac33cdaf9b78fd84a then the change in [[4470209]](https://chromium-review.googlesource.com/c/chromium/src/+/4470209) will need to be reverted.

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/113.0.5672.127..114.0.5735.91?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2023/05/stable-channel-update-for-desktop_30.html)

### CODE REVIEW

**Comment by Ahrotahn** [comment]
Sure thing!  I've added that in a new commit.

**Comment by macchrome** [comment]
To remove tab search button on Windows, Remove flag win-10-tab-search-caption-button needs to be reverted: https://chromium.googlesource.com/chromium/src/+/f395a86902572461006674b9a8d5033e4f5444e7%5E%21/#F0

**Comment by teeminus** [comment]
Builds and runs fine on windows

**Comment by networkException** [comment]
Sorry for the late response again, conferences are keeping me busy.

I'm running into

```
../../components/omnibox/browser/autocomplete_controller.cc:1577:11: error: member access into incomplete type 'AutocompleteScoringModelService'
          ->ScoreAutocompleteUrlMatch(&scoring_model_task_tracker_,
          ^
../../components/omnibox/browser/autocomplete_provider_client.h:34:7: note: forward declaration of 'AutocompleteScoringModelService'
class AutocompleteScoringModelService;
      ^
1 error generated.
```

with both gcc and clang, any idea?

**Comment by Ahrotahn** [comment]
No worries, everyone is donating their own free time for stuff like this.  I haven't seen @PF4Public in a while, I hope they're just enjoying a well-deserved vacation.  

As for the issue you're running into, you need to apply the changes in [[4534915]](https://chromium-review.googlesource.com/c/chromium/src/+/4534915).  Now that I'm thinking about this specifically, I think that change is something I should add to the update since it's specific to us building without tflite.  I'll push new commits with that added soon.

**Review by networkException — APPROVED** [review]

**Review by networkException — APPROVED** [review]

**Comment by networkException** [comment]
As there's an approval from a Windows team member in https://github.com/ungoogled-software/ungoogled-chromium/pull/2366#issuecomment-1571503825 and to not delay a release further I think this is good to merge.

**Comment by PF4Public** [comment]
> I haven't seen @PF4Public in a while, I hope they're just enjoying a well-deserved vacation.

As much as I wanted to, but unfortunately no. I'm sorry for my sudden disappearence, but for a moment I felt overwhelmed by interactions on GitHub and needed to disconnect and take a break. Besides there were some things of utmost importance offline, which were neglected for far too long, so I was there :) somewhere there. 

And now I have a lot of catching up to do :)

**Comment by Ahrotahn** [comment]
I'm glad you're doing alright.  Don't allow yourself to make an obligation out of something that should be a hobby!  I appreciate y'all and the work you share with the world.

**Pull request merged**
