### PR TITLE
Update to Chromium 103.0.5060.53

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 103.0.5060.53.  

Notable changes:

* A removal in 0005-disable-default-extensions.patch due to the removal of the feedback extension in [[3606948]](https://chromium-review.googlesource.com/c/chromium/src/+/3606948)

* PluginsResourceService and WebResourceService were removed in [[3584290]](https://chromium-review.googlesource.com/c/chromium/src/+/3584290), so 0007-disable-web-resource-service.patch is no longer needed and the relevant section in disable-untraceable-urls.patch has been removed.

* Small update to the trk patch due to [[3621976]](https://chromium-review.googlesource.com/c/chromium/src/+/3621976)

* A removal and some new additions to remove-unused-preferences-fields.patch due to [[3627578]](https://chromium-review.googlesource.com/c/chromium/src/+/3627578), [[3637732]](https://chromium-review.googlesource.com/c/chromium/src/+/3637732), and [[3595760]](https://chromium-review.googlesource.com/c/chromium/src/+/3595760)

* disable-formatting-in-omnibox.patch includes the new mobile prefix: [[3596512]](https://chromium-review.googlesource.com/c/chromium/src/+/3596512)

* android\_small/icudtl(\_extra).dat has been removed from update_lists.py due to [[3582190]](https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3582190)

* 'false' has been changed to 'False' in remove-uneeded-ui.patch.  Apparently that's always been wrong, but has been interpreted correctly until [[3603267]](https://chromium-review.googlesource.com/c/chromium/src/+/3603267)

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/102.0.5005.115..103.0.5060.53?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2022/06/stable-channel-update-for-desktop_21.html)

### CODE REVIEW

**Comment by PF4Public** [comment]
Builds and runs 👍🏻

**Review by networkException — DISMISSED** [review]
Looks good, builds and runs

**Comment by Rusenche** [comment]
https://github.com/ungoogled-software/ungoogled-chromium/pull/1994#issuecomment-1162603375

**Review by PF4Public — APPROVED** [review]

**Review by networkException — APPROVED** [review]

**Comment by PF4Public** [comment]
git pull, create the tag, git push

**Comment by networkException** [comment]
hmm should work

**Comment by PF4Public** [comment]
> could it be that your access token doesn't have the permission to modify workflows?

This is the only place, where I use a token with the broadest permission set :)

**Comment by networkException** [comment]
then im out of ideas

**Comment by PF4Public** [comment]
@networkException have you pull-ed already? I wonder if you have https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/test1 https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/test2 and https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/test3?

Actions docs say that creating multiple tags does not fire actions. Those might be some leftover tags, which were pruned, but remained in my local copy.

**Comment by networkException** [comment]
I just pulled those

image

**Comment by PF4Public** [comment]
Ok, I'll remove them and recreate my local copy.

**Pull request merged**
