### PR TITLE
Update to Chromium 127.0.6533.99

### PR DESCRIPTION
**Pull request by networkException**
This PR updates to Chromium 127.0.6533.99.  
There were no changes needed on our end.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/127.0.6533.88..127.0.6533.99?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2024/08/stable-channel-update-for-desktop.html)

### CODE REVIEW

**Comment by Cubik65536** [comment]
Builds and runs fine on macOS (arm64).

**Comment by clickot** [comment]
portable linux builds fine and runs at least on manjaro, ubuntu 20.04+24.04 and fedora 40

**Comment by networkException** [comment]
Critical CVE anyone? @ungoogled-software/core

I'll take one approval for an admin merge by now :P

**Review by PF4Public — APPROVED** [review]
Sorry, was offline.

**Comment by networkException** [comment]
All good, thanks :)

**Pull request merged**
