### PR TITLE
Update to Chromium 117.0.5938.62/63

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 117.0.5938.62/63.  

Notes:  

* disable-fonts-googleapis-references.patch had some removals due to [[4653008]](https://chromium-review.googlesource.com/c/chromium/src/+/4653008) and [[4633219]](https://chromium-review.googlesource.com/c/chromium/src/+/4633219)

* safebrowsing patch: the x509_certificate.h include has finally been added to devtools_window.cc in [[4670702]](https://chromium-review.googlesource.com/c/chromium/src/+/4670702)

* remove-unused-preferences-fields.patch:  
  * I've removed the removals of the settings strings.  This has been causing problems for a while and recent changes in [[4616226]](https://chromium-review.googlesource.com/c/chromium/src/+/4616226) and many new changes for future versions are going to make this worse.  
  * new inclusions for [[4748960]](https://chromium-review.googlesource.com/c/chromium/src/+/4748960) and [[4701763]](https://chromium-review.googlesource.com/c/chromium/src/+/4701763)

* disable-web-environment-integrity.patch has been updated for the changes in [[4681552]](https://chromium-review.googlesource.com/c/chromium/src/+/4681552) and [[4570836]](https://chromium-review.googlesource.com/c/chromium/src/+/4570836)

* remove-uneeded-ui.patch had a removal for [[4665525]](https://chromium-review.googlesource.com/c/chromium/src/+/4665525)

* Fixed a regression with the clear data on exit flag: https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/259

* Fixed an issue causing the save password view not to show: https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/266

<br>

* Due to [[4179383]](https://chromium-review.googlesource.com/c/chromium/src/+/4179383) the experiments button will now be shown for non-stable releases.  This can be disabled through `chrome://flags/#chrome-labs` or launching with `--disable-features=ChromeLabs` (or modifying [chrome_labs_utils.cc](https://source.chromium.org/chromium/chromium/src/+/refs/tags/117.0.5938.35:chrome/browser/ui/toolbar/chrome_labs_utils.cc;l=142)).

* <del>Changes to Cirrus CI's limits are causing one of our checks to fail (some prior discussion in #2478).</del>

* depot_tools.patch was updated for the changes in [[4836379]](https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/4836379).

### CODE REVIEW

**Comment by PF4Public** [comment]
> * Changes to Cirrus CI's limits are causing one of our checks to fail (some prior discussion in [Update to Chromium 116.0.5845.140/141 #2478](https://github.com/ungoogled-software/ungoogled-chromium/pull/2478)).

Seems to be failing still :( Chromium unpacked takes 13G, so maybe cutting 3G was not enough

**Comment by Ahrotahn** [comment]
They've started including rust sources in the tarball which is why it's larger.  This also means more memory is needed for Cirrus, so I've added a commit to bump that up a bit.  I'll spend some time later to see about adding a new switch to exclude those large unneeded directories.  That would reduce the space needed as well as the time it takes to complete.

**Comment by networkException** [comment]
It seems like Google removed (?) this build from their releases api again?

**Comment by Ahrotahn** [comment]
Maybe there was a temporary issue?  Seems to be available for me at the moment:
[Blog post](https://chromereleases.googleblog.com/2023/09/early-stable-update-for-desktop.html)
[Release table](https://chromiumdash.appspot.com/releases)

**Review by PF4Public — DISMISSED** [review]
Builds and runs (on Linux at least)

**Comment by PF4Public** [comment]
I wonder what "use this one" does
```c
const FeatureEntry::FeatureVariation kChromeLabsVariations[] = {
    {" use this one!", kChromeLabsEnabledInFlags,
     std::size(kChromeLabsEnabledInFlags), nullptr}};
```
image

**Comment by networkException** [comment]
I have to say I'm kinda starting to dislike these early stable bumps. They are nice for rebasing our patches earlier but when these get tagged we're rolling out changes that have only been deployed to a fraction of vanilla chromium users

**Comment by PF4Public** [comment]
@networkException I share your concerns. Early stable releases also prepare another difficulty (of micromanagement) for us when in the future the pace of releases is increased. 

We may completely ignore them and I'll submit a PR for excluding them from `new_version_check.yml`. What do you think?

**Comment by PF4Public** [comment]
@Ahrotahn Would you have an opportunity to look at https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/266#?

**Review by PF4Public — APPROVED** [review]
Builds and runs

**Review by networkException — APPROVED** [review]
Builds and runs :+1:

**Pull request merged**
