### PR TITLE
Update to Chromium 104.0.5112.81

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 104.0.5112.81.  

Notes:
* There were some removals to `remove-unused-preferences-fields.patch` due to [[3677133]](https://chromium-review.googlesource.com/c/chromium/src/+/3677133) and [[3660411]](https://chromium-review.googlesource.com/c/chromium/src/+/3660411)
* I made a small change to the search engine collection patch due to the removal of the switch check in [[3648297]](https://chromium-review.googlesource.com/c/chromium/src/+/3648297)
* `fix-building-without-one-click-signin.patch` and the `enable_one_click_signin` flag has been removed due to it's removal in [[3637158]](https://chromium-review.googlesource.com/c/chromium/src/+/3637158)
* A new UI removal for the Privacy Guide promo and section in the privacy settings due to [[3654437]](https://chromium-review.googlesource.com/c/chromium/src/+/3654437).  This will be a short-lived change since it's removal has already been merged in [[3718094]](https://chromium-review.googlesource.com/c/chromium/src/+/3718094)

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/103.0.5060.134..104.0.5112.81?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2022/08/stable-channel-update-for-desktop.html)

### CODE REVIEW

**Comment by a61kt** [comment]
For archlinux .. the   remove-no-opaque-pointers-flag.patch its broken  

My bugfix (rerun this patch)
https://build.opensuse.org/package/rdiff/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium22?linkrev=base&rev=26

**Comment by a61kt** [comment]
i got an error
[ 2427s] [22396/50767] CXX obj/third_party/tflite_support/tflite_support/metadata_extractor.o
[ 2427s] FAILED: obj/third_party/tflite_support/tflite_support/metadata_extractor.o 
[ 2427s] clang++ -MMD -MF obj/third_party/tflite_support/tflite_support/metadata_extractor.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DLIBYUV_DISABLE_NEON -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I../../third_party/tflite_support/src -I../../third_party/tflite_support/src/tensorflow_lite_support -Igen/shim_headers/re2_shim -Igen/shim_headers/zlib_shim -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/libyuv/include -Igen/shim_headers/minizip_shim -I../../third_party/abseil-cpp -I../../third_party/flatbuffers/src/include -I../../third_party/protobuf/src -Igen/protoc_out -Igen/third_party/tflite_support/src -Igen/third_party/tflite/src -I../../third_party/boringssl/src/include -I../../third_party/libzip/src -I../../third_party/tensorflow-text/src -I../../third_party/tflite/src -I../../third_party/utf/src -I../../third_party/utf/src/include -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -flto=thin -fsplit-lto-unit -fwhole-program-vtables -no-canonical-prefixes -ftrivial-auto-var-init=pattern -fno-omit-frame-pointer -fsanitize=cfi-vcall -fsanitize-ignorelist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-unused-but-set-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wno-unqualified-std-cast-call -Wno-comment -Wno-extern-c-compat -Wno-implicit-function-declaration -Wno-sign-compare -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-unused-variable -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-implicit-function-declaration -std=c++17 -Wno-trigraphs -fno-aligned-new -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -frtti  -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wno-builtin-macro-redefined -Wno-unknown-warning-option -c ../../third_party/tflite_support/src/tensorflow_lite_support/metadata/cc/metadata_extractor.cc -o obj/third_party/tflite_support/tflite_support/metadata_extractor.o
[ 2427s] ../../third_party/tflite_support/src/tensorflow_lite_support/metadata/cc/metadata_extractor.cc:24:10: fatal error: 'contrib/minizip/ioapi.h' file not found
[ 2427s] #include "contrib/minizip/ioapi.h"

**Comment by PF4Public** [comment]
> The Beta channel has been updated to 104.0.5112.81 for Windows and 104.0.5112.79 for   Mac and Linux.

**Review by networkException — APPROVED** [review]
Builds and runs fine

Note that I used 104.0.5112.79, there's no difference on our side to .81

**Comment by a61kt** [comment]
@networkException and works well on a clean chroot (obs)

**Review by PF4Public — APPROVED** [review]
Builds and runs 👍🏻

**Comment by networkException** [comment]
I think we can ship this

**Pull request merged**
