### PR TITLE
Update to Chromium 107.0.5304.62/63/68

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 107.0.5304.62/63/68.

Notable changes:
*  SafeMoveHelper has been renamed to FileSystemAccessSafeMoveHelper in [[3872333]](https://chromium-review.googlesource.com/c/chromium/src/+/3872333).
* Changes in remove-unused-preferences-fields.patch due to [[3804886]](https://chromium-review.googlesource.com/c/chromium/src/+/3804886).
* The fingerprinting patches have been updated due to changes in [[3886298]](https://chromium-review.googlesource.com/c/chromium/src/+/3886298).
* Linux users will be affected by the changes in [[3947549]](https://chromium-review.googlesource.com/c/chromium/src/+/3947549).  Building will now require either including a statically built libffi or enabling the `use_system_libwayland` and `use_system_libwayland_server` build flags to use the system's library like in previous versions.  Currently `use_system_libwayland` also sets `use_system_libwayland_client`, but both the client and server flags will be removed in an upcoming version and only `use_system_libwayland` will be required.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/106.0.5249.119..107.0.5304.68?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop_25.html)

### CODE REVIEW

**Comment by PF4Public** [comment]
Will it still run under X11? I'm confused.

**Comment by Ahrotahn** [comment]
Yes it still works on X11, I'm running it on an X11 desktop currently.  
That change only affects how things are built.  Previously the system's library was used by default, but with the recent changes building now attempts to use included code to build statically and will fail if libffi_pic.a is not found.  This is supplied prebuilt by gclient rather than being built along with everything else.  So you would either need to add building that into your process or set the buildflags mentioned in the first post.

**Comment by Ahrotahn** [comment]
I also ran into an unrelated, small, upstream-introduced issue where the scrollbar disappears after a while when running with OverlayScrollbar enabled.  This seems to be due to some optimizations that got enabled which can be reverted by removing this line for now:
```diff
--- a/third_party/blink/renderer/platform/runtime_enabled_features.json5
+++ b/third_party/blink/renderer/platform/runtime_enabled_features.json5
@@ -2273,7 +2282,6 @@
       // Whether to enable scroll update optimizations. See crbug.com/1346789.
       name: "ScrollUpdateOptimizations",
       base_feature: "ScrollUpdateOptimizations",
-      status: "stable",
     },
     {
       name: "SecureContextFixForSharedWorkers",
```

**Comment by PF4Public** [comment]
Builds and runs 👍🏻

**Comment by PF4Public** [comment]
@Ahrotahn Are fingerprinting patches troublesome with each major update?

**Comment by Ahrotahn** [comment]
No more than most of the other patches.  Though they touch areas of the codebase that get a lot of traffic so they'll often have changes.

**Review by PF4Public — COMMENTED** [review]
Builds and runs 👍🏻

**Review by PF4Public — APPROVED** [review]

**Review by networkException — APPROVED** [review]

**Comment by networkException** [comment]
Seems like the process to install extensions using https://github.com/NeverDecaf/chromium-web-store has changed to be less reliable, idk if anything can be done on our side though.

**Comment by PF4Public** [comment]
Are we ready to merge?

@networkException How exactly it got unreliable?

**Comment by Ahrotahn** [comment]
I encountered the same thing yesterday.  It tried to update the extension and failed the first time, but it succeeded the second.  Hopefully that is just a one-time thing.

**Pull request merged**
